### PR TITLE
Team TurboSailers submission for 2022/rehearsal event.

### PR DESCRIPTION
**Pull request by Anvesh-Som**
This submission tackles tasks #1 Station Keeping (Localization by sensor fusion and then controlling wamv)

### CODE REVIEW

**Comment by caguero** [comment]
Could you please rename your DockerHub link to lowercase? Otherwise it doesn't work. I did it manually for testing your submission.

* [x] Compliance tests for component and propulsion configurations passed.
* [x] Successfully able to access Docker image.

Verified that the WAMV is active in the following tasks:
* [x] Stationkeeping
* [ ] Wayfinding
* [ ] Perception 
* [ ] Wildlife
* [ ] Gymkhana
* [ ] Scan, Dock, Deliver

**Review by caguero — CHANGES_REQUESTED** [review]
Thanks for the submission. Here are the issues I found in your submission from my initial testing:

* The content in `dockerhub_image.txt` should use lowercase.
* When running the station keeping task, I see the following message in the terminal: `Sending forward command`. Then, the WAM-V moves forward in a straight line. Is this expected? It looks like you're running the example behavior that we provided in the tutorial.

**Comment by Anvesh-Som** [comment]
I am terribly sorry, Yes I submitted docker image of tutorial by mistake. Is it ok if I sent another pull request with the actual workspace? (fixed the upper case typo too)

**Comment by M1chaelM** [comment]
> I am terribly sorry, Yes I submitted docker image of tutorial by mistake. Is it ok if I sent another pull request with the actual workspace? (fixed the upper case typo too)

Yes, please send it and let us know when it's ready to test. Thanks!

**Comment by M1chaelM** [comment]
Oops, I see the new request now. Closing this PR and continuing on PR #62.

**Pull request closed without merging**
