### PR TITLE
2022 test phase3

### PR DESCRIPTION
**Pull request by FrancisGoncalves**
It should work for task 1. We tested it and it had a weird behavior that it did not seem to be related to the boat controller but with something else we do not understand.

Thank you,
Wazzu Worms

### CODE REVIEW

**Comment by M1chaelM** [comment]
* [x] Compliance tests for component and propulsion configurations passed.
* [x] Successfully able to access Docker image.

Verified that the WAMV is active in the following tasks:
* [x] Stationkeeping
* [ ] Wayfinding
* [ ] Perception 
* [ ] Wildlife
* [ ] Gymkhana
* [ ] Scan, Dock, Deliver

**Comment by M1chaelM** [comment]
OK, certainly your system is working and communicating with the scoring server. I see the WAMV being controlled by your code. For some reason, the movement is not what you probably want. If this works well on your local machine, then the most likely problem is that you are missing some dependency on Docker image.

To try to guess what this might be, I am running the trial manually as described in [this section of the troubleshooting tutorial](https://github.com/osrf/vrx/wiki/tutorials-vrx_docker_manual_trial). There is no obvious error output from executing your entrypoint, but when I try to call your Python scripts individually it looks like they may have unsatisfied dependencies. For example:
```
root@44565f47f383:/# python3 VehicleGoal.py 
Traceback (most recent call last):
  File "VehicleGoal.py", line 3, in <module>
    import rospy
ModuleNotFoundError: No module named 'rospy'
```
Executing a Python3 shell shows several of your imports appear to be failing:
```
root@44565f47f383:/# head VehicleGoal.py 
#!/usr/bin/env python
# license removed for brevity
import rospy
from std_msgs.msg import Float32
from std_msgs.msg import String
from geometry_msgs.msg import Twist
from geometry_msgs.msg import Pose
import numpy as np
import math

root@44565f47f383:/# python3
Python 3.8.10 (default, Mar 15 2022, 12:22:08) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from std_msgs.msg import Float32
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'std_msgs'
>>> import geometry_msgs.msg
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'geometry_msgs'
>>> import numpy as np
>>> import math
>>> 
```
This is about as far as I should probably dig into the issue, but I hope it helps. If there's something else you'd like me to check let me know.

**Comment by FrancisGoncalves** [comment]
Thank you very much Michael. I think that helps. We thought rospy and the other messages packages were automatically installed since we have ROS in the Docker Image but we will try to solve this issue. It is also weird that these errors do not appear when running the entrypoint. I will get back to you tomorrow with updates.

Thank you again,
Francisco
________________________________

**Comment by M1chaelM** [comment]
Revisiting this, I'm a bit stumped. As you pointed out, the import errors were the result of not sourcing the environment, and they don't occur during a normal run of the script. I also don't see any evidence that you are missing dependencies, and you appear to have built the latest version of vrx.

If the behavior is still different from what you see on a local machine, the only other common gotcha I can think of is that your local machine might be using older versions of something. This doesn't seem very likely, but just to make sure: is the system where you are seeing the desired behavior using an updated version of the vrx repository?

**Comment by FrancisGoncalves** [comment]
Yes, we have it all up to date. It is unfortunate that our Docker Image is not working as expected, but the main purpose of our enrollment in this competition was to learn more about ROS, simulation environments, computer vision, and control. I think most of these goals were accomplished, so, although we are a bit frustrated, we are also happy with what we did. Thank you for providing this competition and also for trying to help us debug this until the last minute.

Sincerely,
Francisco
________________________________

**Comment by M1chaelM** [comment]
OK, thanks for your hard work on this! Out of curiosity, what is the behavior / score you are seeing when you run this on your host?

Since your WAMV is showing activity on the task you attempted, I think we can merge this. However, if you want to make a correction to address a discrepancy caused by the docker image configuration you have until 11:59PM PT tonight.

**Comment by FrancisGoncalves** [comment]
I will send you some videos of our wamv behavior and our scores by tomorrow!

Thank you,
Francisco
________________________________

**Comment by FrancisGoncalves** [comment]
Goncalves, Francisco has shared a OneDrive for Business file with you. To view it, click the link below.
<https://emailwsu-my.sharepoint.com/personal/francisco_goncalves_wsu_edu/Documents/Attachments/VRX2022_WazzuWorms.zip>
[https://r1.res.office365.com/owa/prem/images/dc-zip_20.png]<https://emailwsu-my.sharepoint.com/personal/francisco_goncalves_wsu_edu/Documents/Attachments/VRX2022_WazzuWorms.zip>
VRX2022_WazzuWorms.zip<https://emailwsu-my.sharepoint.com/personal/francisco_goncalves_wsu_edu/Documents/Attachments/VRX2022_WazzuWorms.zip>

Hi Michael,

Here are some videos of the behavior of our wamv in the first three tasks (Station Keeping, Wayfinding, and Perception). In the perception task we kept getting an error of 2.0 because we were miscalculating the coordinates of the buoys, and we did not have time to fix it.

Thank you very much,
Francisco
________________________________

**Comment by FrancisGoncalves** [comment]
To view VRX2022_WazzuWorms.zip, sign in<https://emailwsu-my.sharepoint.com/personal/francisco_goncalves_wsu_edu/_layouts/15/acceptinvite.aspx?invitation=%7BE468497E%2DD489%2D4279%2D97E5%2DF1D55BED96E0%7D&listId=6e3b3854%2Dc2d2%2D4087%2D9c37%2D98e8e2f44043&itemId=0364b3d8%2D28de%2D4909%2Db970%2D25b210687ab1> or create an account.

**Pull request merged**
