### PR TITLE
MacU Dress Rehearsal

### PR DESCRIPTION
**Pull request by altmattr**

### CODE REVIEW

**Comment by M1chaelM** [comment]
* [x] Compliance tests for component and propulsion configurations passed.
* [x] Successfully able to access Docker image.

Verified that the WAMV is active in the following tasks:
* [ ] Stationkeeping
* [ ] Wayfinding
* [ ] Perception 
* [ ] Wildlife
* [ ] Gymkhana
* [ ] Scan, Dock, Deliver

**Comment by M1chaelM** [comment]
I am seeing no activity in the stationkeeping task. Is this expected? If you could please say which tasks your solution is attempting it would help us verify. Thanks!

**Comment by altmattr** [comment]
Thanks Michael

We fell behind in getting the submission image working so we’ve only been able to submit one that does nothing im afraid.

On the plus side, we got all the plumbing working :)

Matt

On 16 Mar 2022, at 9:14 am, M1chaelM ***@***.***> wrote:

﻿

I am seeing no activity in the stationkeeping task. Is this expected? If you could please say which tasks your solution is attempting it would help us verify. Thanks!

—
Reply to this email directly, view it on GitHub<https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fosrf%2Fvrx-events%2Fpull%2F41%23issuecomment-1068519503&data=04%7C01%7Cmatthew.roberts%40mq.edu.au%7C648fb20724d6409930d708da06d1211b%7C82c514c1a7174087be06d40d2070ad52%7C0%7C0%7C637829792547177560%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=%2F24xsI6oCWMMAkfFPR1CXtNyjmRvbHpALAIm6U0t1I0%3D&reserved=0>, or unsubscribe<https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAAMQFYMA3LXFUSSYEE3D7Q3VAEDSZANCNFSM5QXPS6YQ&data=04%7C01%7Cmatthew.roberts%40mq.edu.au%7C648fb20724d6409930d708da06d1211b%7C82c514c1a7174087be06d40d2070ad52%7C0%7C0%7C637829792547177560%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=gXeMS%2F82BrNKyXWvaHX2M%2BuNBRFv6UgNGXn60OO8nGc%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675> or Android<https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.

**Comment by M1chaelM** [comment]
No problem! This is a reason we have a dress rehearsal.

**Review by M1chaelM — APPROVED** [review]
Working as expected. Thanks for your submission! The next step is to evaluate run the docker image in the VRX simulation with the tasks/trials over the next few days.

**Pull request merged**
