### PR TITLE
Team OSRF Submission for 2023/Hello World.

### PR DESCRIPTION
**Pull request by lw76**
Team Inspiration's Hello world submission for VRX

### CODE REVIEW

**Review by caguero — CHANGES_REQUESTED** [review]
Thanks for your VRX submission!

* [ ] Compliance tests for component and propulsion configurations passed.
* [ ] Successfully able to access Docker image.
* [x] Your video is reachable.
* [ ] Verified that the WAMV is active in the stationkeeping task.

Your Docker image is not reachable. Looking at your Dockerhub, it looks like you're missing the tag name:

```
lindsayalwright/20230905test-img:1

```

Could you please review the phase 1 submission tutorial to follow the file name conventions?

https://github.com/osrf/vrx/wiki/vrx_2023-phase1_hello_world#submission-format

Your WAM-V config files do not agree with the expected names. By spotting at your `component_config.yaml`, I can see that the `wamv_pinger`->`name` field should be renamed to `sensor_name`.

**Comment by lw76** [comment]
Revised files to match format required in config files and corrected the DockerHub link

**Comment by caguero** [comment]
> Revised files to match format required in config files and corrected the DockerHub link

@lw76 , I still see the WAM-V files named incorrectly. Could you please update them?

**Comment by lw76** [comment]
File names have been changed

**Review by caguero — APPROVED** [review]
Thanks for the update! I can generate your WAM-V successfully now. Approving.

I see WAM-V activity, it looks like the WAM-V slowly moves forward constantly. I guess this is expected. 

I recommend you to go through the submission [instructions from the phase 1 tutorial](https://github.com/osrf/vrx/wiki/vrx_2023-phase1_hello_world#submission-testing) to test your solution (when ready) before phase 2. You can do that by yourself to make sure things are working before you make the next submission.

**Pull request merged**
