### PR TITLE
Team Australis2 submission for 2022/rehearsal event

### PR DESCRIPTION
**Pull request by JonathanWheare**
This is team Australis^2 submission for the rehearsal event.  Our submission is still under heavy development, so should attempt tasks #1 and #2, but may not successfully perform the remaining tasks.

### CODE REVIEW

**Comment by M1chaelM** [comment]
Thanks for your submission! Could you please update the `dockerhub_image.txt` file to include the tag for your submission? Without the tag, the pull command fails.

**Comment by M1chaelM** [comment]
* [x] Compliance tests for component and propulsion configurations passed.
* [x] Successfully able to access Docker image.

Verified that the WAMV is active in the following tasks:
* [x] Stationkeeping
* [x] Wayfinding
* [ ] Perception 
* [ ] Wildlife
* [ ] Gymkhana
* [ ] Scan, Dock, Deliver

**Comment by JonathanWheare** [comment]
> Thanks for your submission! Could you please update the `dockerhub_image.txt` file to include the tag for your submission? Without the tag, the pull command fails.

Hi Michael,

I have added a tag to the docker image.  Can you please test and let me know if this resolves the issue.

Regards,
Jonathan.

**Review by M1chaelM — APPROVED** [review]
The latest commit addresses the only outstanding issue. This now works as expected. Thanks for the submission! The next step is to evaluate run the docker image in the VRX simulation with the tasks/trials over the next few days.

**Pull request merged**
