### PR TITLE
2023 vrxphase1 robotics and circuits1 osrf

### PR DESCRIPTION
**Pull request by kishikaS**

### CODE REVIEW

**Review by caguero — CHANGES_REQUESTED** [review]
Thanks for your VRX submission!

* [x]  Your video is reachable.
* [x] Compliance tests for component and propulsion configurations passed.
* [ ] Successfully able to access Docker image.
* [ ] Verified that the WAMV is active in the stationkeeping task.

Your file containing the link to your Docker image is incorrectly named. Could you please rename it to `dockerhub_image.txt`?

I don't see activity in your WAM-V during stationkeeping because the propellers aren't moving. I see these messages over and over in the terminal:

```
publishing #400: std_msgs.msg.Float64(data=2.0)
publishing #400: std_msgs.msg.Float64(data=2.0)
```

If this isn't expected behavior, please update and retest your submission following the [instructions from the phase 2 tutorial](https://github.com/osrf/vrx/wiki/vrx_2023-phase2_dress_rehearsal#submission-testing).

**Comment by kishikaS** [comment]
Till when can we submit the changes?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by caguero** [comment]
> Till when can we submit the changes?

2023, October 4, 23:59 PDT was the deadline for submitting a correction. We'll accept a late submission as your change is pretty minimum. You only need to fix the naming issue. The feedback about your WAM-V is only useful in case you didn't know but is not required that your solution actually works to go to phase 3.

**Comment by caguero** [comment]
@kishikaS , friendly ping to rename your file.

**Comment by caguero** [comment]
Using #131 instead.

**Pull request closed without merging**
