### PR TITLE
Phase 3 submission for ANT61

### PR DESCRIPTION
**Pull request by limenutt**

### CODE REVIEW

**Comment by caguero** [comment]
Thanks for the submission.

* [x] Compliance tests for component and propulsion configurations passed.
* [x] Successfully able to access Docker image.

Is your intent to tackle all tasks? I don't see your WAM-V moving much on the `wayfinding task`. Just checking to see if this the expected behavior.

Verified that the WAMV is active in the following tasks:
* [x] Stationkeeping
* [ ] Wayfinding
* [ ] Perception 
* [ ] Wildlife
* [ ] Gymkhana
* [ ] Scan, Dock, Deliver

**Comment by caguero** [comment]
> Thanks for the submission.
> 
> * [x]  Compliance tests for component and propulsion configurations passed.
> * [x]  Successfully able to access Docker image.
> 
> Is your intent to tackle all tasks? I don't see your WAM-V moving much on the `wayfinding task`. Just checking this is the expected behavior.
> 
> Verified that the WAMV is active in the following tasks:
> 
> * [x]  Stationkeeping
> * [ ]  Wayfinding
> * [ ]  Perception
> * [ ]  Wildlife
> * [ ]  Gymkhana
> * [ ]  Scan, Dock, Deliver

**Comment by limenutt** [comment]
We did station keeping only, it's intentional. 
Thanks for checking!

**Comment by caguero** [comment]
> We did station keeping only, it's intentional. Thanks for checking!

Thanks! I'm approving then.

**Review by caguero — APPROVED** [review]

**Pull request merged**
