### PR TITLE
2023 rehearsal team osrf

### PR DESCRIPTION
**Pull request by lw76**
added capabilities to back up and hold in place with thrusters on

### CODE REVIEW

**Comment by caguero** [comment]
If this is a resubmission, could you target your files to the same team directory that you originally used? It should be `inspiration/`

**Comment by caguero** [comment]
@lw76 , friendly ping.

**Comment by lw76** [comment]
Hello @caguero , I will fix this today!

**Comment by lw76** [comment]
I just docker pushed changes to the image. Do you see the changes now?

**Comment by caguero** [comment]
@lw76 , there are conflicts in your pull request. Could you resolve them please?

**Comment by lw76** [comment]
I've just pushed code with the resolved merge conflicts now. Does this work?

**Comment by caguero** [comment]
Your docker image isn't installing the `ros-humble-ros-gzgarden` package. This package is necessary to access some of the messages used by the `gz<-->ros2` bridge. If you don't install it, you won't be able to subscribe to the /vrx/task/info` topic.

See https://github.com/osrf/vrx-docker/blob/master/mwes/2023/vrx_2023_simple/Dockerfile#L35-L37 and https://github.com/osrf/vrx-docker/blob/master/mwes/2023/vrx_2023_simple/Dockerfile#L47-L53

**Comment by caguero** [comment]
Closing this pull request as we're approaching phase 3. Consider my last comment when you prepare your final submission.

**Pull request closed without merging**
