### PR TITLE
USYD ROBOTX Submission 2

### PR DESCRIPTION
**Pull request by JohnSumskas**
Fixed and updated docker image.
We expect activity in all tasks.

### CODE REVIEW

**Comment by M1chaelM** [comment]
Should the Docker image repository or tag have changed? I'm seeing the same content for dockerhub_image.txt and pulling it gives me an image with an identical  digest.

**Comment by JohnSumskas** [comment]
It should be a different digest.
I now have updated it to point to a different tag (v2.2022) to ensure this.

Let me know if there still is an issue. thanks.

**Comment by M1chaelM** [comment]
Ah, I may have downloaded the new one without realizing it before the previous PR was closed. The digest I have is:
```
b3e9b466f778c1716afbc97ea810e6e7b1adeaaf064bcf385eba9bf3025bac8f
```

**Comment by M1chaelM** [comment]
* [x] Compliance tests for component and propulsion configurations passed.
* [x] Successfully able to access Docker image.

Verified that the WAMV is active in the following tasks:
* [x] Stationkeeping
* [x] Wayfinding
* [x] Perception 
* [x] Wildlife
* [x] Gymkhana
* [x] Scan, Dock, Deliver

**Comment by JohnSumskas** [comment]
This looks good. Thanks!

**Comment by M1chaelM** [comment]
I'm seeing activity in all tasks. The perception task produces a lot of terminal output, but it doesn't seem to be publishing anything to `/vrx/perception/landmark`.

Early in the trial, I see the following:

```
[ WARN] [1649828948.089760133, 3.840000000]: Failed to meet update rate! Took 3.8233333329999998895
[ WARN] [1649828948.108881896, 3.857000000]: navsat_transform, Parameter 'broadcast_utm_transform' has been deprecated. Please use'broadcast_cartesian_transform' instead.
[ WARN] [1649828948.121190572, 3.868000000]: Could not obtain transform from wamv/imu_wamv_link to wamv/base_link. Error was "wamv/imu_wamv_link" passed to lookupTransform argument source_frame does not exist. 

[ WARN] [1649828948.455732186, 4.200000000]: Transform from wamv/imu_wamv_link to wamv/base_link was unavailable for the time requested. Using latest instead.

[ WARN] [1649828948.469235668, 4.213000000]: Transform from wamv/gps_wamv_link to wamv/base_link was unavailable for the time requested. Using latest instead.

[ WARN] [1649828948.825227701, 4.560000000]: Shutdown request received.
[ WARN] [1649828948.825482090, 4.560000000]: Reason given for shutdown: [[/wamv/joint_states_relay] Reason: new node registered with same name]
[ WARN] [1649828948.849356046, 4.578000000]: Shutdown request received.
[ WARN] [1649828948.849572728, 4.578000000]: Reason given for shutdown: [[/wamv/robot_localization/navsat_transform_node] Reason: new node registered with same name]
[ WARN] [1649828948.857412393, 4.578000000]: Shutdown request received.
[ WARN] [1649828948.861492169, 4.583000000]: Reason given for shutdown: [[/wamv/rob_st_pub] Reason: new node registered with same name]
[ WARN] [1649828948.871725807, 4.588000000]: Shutdown request received.
[ WARN] [1649828948.871814914, 4.588000000]: Reason given for shutdown: [[/wamv/robot_localization/ekf_localization] Reason: new node registered with same name]
[ WARN] [1649828948.896089535, 4.601000000]: Shutdown request received.
[ WARN] [1649828948.896127874, 4.601000000]: Reason given for shutdown: [[/wamv/odom_relay] Reason: new node registered with same name]
[ WARN] [1649828948.915963807, 4.612000000]: Shutdown request received.
[ WARN] [1649828948.920670954, 4.617000000]: Reason given for shutdown: [[/map_tf_static] Reason: new node registered with same name]
[ WARN] [1649828948.997268997]: Shutdown request received.
[ WARN] [1649828949.006405223, 4.676000000]: Reason given for shutdown: [[/wamv/rob_st_pub] Reason: new node registered with same name]
[ WARN] [1649828949.029151435, 4.685000000]: Failed to meet update rate! Took 4.6850000000000004974
[ WARN] [1649828949.044075148, 4.686000000]: navsat_transform, Parameter 'broadcast_utm_transform' has been deprecated. Please use'broadcast_cartesian_transform' instead.
[ INFO] [1649828949.048928735]: start
start
[ WARN] [1649828949.060474752, 4.689000000]: Failed to meet update rate! Took 4.6723333330000000885
[ INFO] [1649828947.862796027]: Waiting for valid clock time...
[ INFO] [1649828948.092863200, 3.843000000]: Valid clock time received. Starting node.
[ INFO] [1649828948.118183963, 3.865000000]: Datum (latitude, longitude, altitude) is (-33.722562, 150.670000, 0.000000)
[ INFO] [1649828948.118207961, 3.865000000]: Datum UTM coordinate is (284109.543449, 6266167.257270) zone 56
[ INFO] [1649828948.118231256, 3.865000000]: Initial odometry pose is Origin: (0 0 0)
Rotation (RPY): (0, -0, 0)

[ INFO] [1649828948.180630568, 3.913000000]: Corrected for magnetic declination of 0.000000, user-specified offset of 0.000000 and meridian convergence of 0.022585. Transform heading factor is now 0.022585
[ INFO] [1649828948.180663213, 3.913000000]: Transform world frame pose is: Origin: (0 0 0)
Rotation (RPY): (0, -0, 0)

[ INFO] [1649828948.180684590, 3.913000000]: World frame->cartesian transform is Origin: (-425549.27741587883793 -6258152.9336737161502 0)
Rotation (RPY): (0, 0, -0.022585452840638349514)

[ WARN] [1649828949.080054591]: Shutdown request received.
[ WARN] [1649828949.083505618, 4.726000000]: Reason given for shutdown: [[/map_tf_static] Reason: new node registered with same name]
[ WARN] [1649828949.109016737, 4.750000000]: Failed to meet update rate! Took 0.044333333000000002544
[ WARN] [1649828949.169998821, 4.800000000]: Could not obtain transform from wamv/imu_wamv_link to wamv/base_link. Error was "wamv/base_link" passed to lookupTransform argument target_frame does not exist. 

[ WARN] [1649828949.209275406, 4.826000000]: Shutdown request received.
[ WARN] [1649828949.209330300, 4.826000000]: Reason given for shutdown: [[/wamv/robot_localization/navsat_transform_node] Reason: new node registered with same name]
[ INFO] [1649828948.787656462]: Waiting for valid clock time...
[ INFO] [1649828949.032552575, 4.686000000]: Valid clock time received. Starting node.
[ INFO] [1649828949.079951264, 4.723000000]: Datum (latitude, longitude, altitude) is (-33.722562, 150.670000, 0.000000)
[ INFO] [1649828949.079998133, 4.723000000]: Datum UTM coordinate is (284109.543449, 6266167.257270) zone 56
[ INFO] [1649828949.080029785, 4.723000000]: Initial odometry pose is Origin: (0 0 0)
Rotation (RPY): (0, -0, 0)

[ INFO] [1649828949.123108482, 4.760000000]: Corrected for magnetic declination of 0.000000, user-specified offset of 0.000000 and meridian convergence of 0.022585. Transform heading factor is now 0.022585
[ INFO] [1649828949.123134999, 4.760000000]: Transform world frame pose is: Origin: (0 0 0)
Rotation (RPY): (0, -0, 0)

[ INFO] [1649828949.123151524, 4.760000000]: World frame->cartesian transform is Origin: (-425549.27741587883793 -6258152.9336737161502 0)
Rotation (RPY): (0, 0, -0.022585452840638349514)

[ WARN] [1649828949.375211999, 4.979000000]: navsat_transform, Parameter 'broadcast_utm_transform' has been deprecated. Please use'broadcast_cartesian_transform' instead.
[ WARN] [1649828949.542314266, 5.106000000]: Shutdown request received.
[ WARN] [1649828949.542577245, 5.106000000]: Reason given for shutdown: [[/wamv/robot_localization/navsat_transform_node] Reason: new node registered with same name]
[ WARN] [1649828949.563669608, 5.121000000]: navsat_transform, Parameter 'broadcast_utm_transform' has been deprecated. Please use'broadcast_cartesian_transform' instead.
[ WARN] [1649828949.657806385, 5.218000000]: Shutdown request received.
[ WARN] [1649828949.657847968, 5.218000000]: Reason given for shutdown: [[/wamv/robot_localization/navsat_transform_node] Reason: new node registered with same name]
Unable to init server: Could not connect: Connection refused
[ INFO] [1649828949.197584253]: Waiting for valid clock time...
[ INFO] [1649828949.358999893, 4.968000000]: Valid clock time received. Starting node.
[ INFO] [1649828949.384722594, 4.988000000]: Datum (latitude, longitude, altitude) is (-33.722562, 150.670000, 0.000000)
[ INFO] [1649828949.384745159, 4.988000000]: Datum UTM coordinate is (284109.543449, 6266167.257270) zone 56
[ INFO] [1649828949.384768807, 4.988000000]: Initial odometry pose is Origin: (0 0 0)
Rotation (RPY): (0, -0, 0)

[ INFO] [1649828949.449124951, 5.021000000]: Corrected for magnetic declination of 0.000000, user-specified offset of 0.000000 and meridian convergence of 0.022585. Transform heading factor is now 0.022585
[ INFO] [1649828949.449158329, 5.021000000]: Transform world frame pose is: Origin: (0 0 0)
Rotation (RPY): (0, -0, 0)

[ INFO] [1649828949.449179820, 5.021000000]: World frame->cartesian transform is Origin: (-425549.27741587883793 -6258152.9336737161502 0)
Rotation (RPY): (0, 0, -0.022585452840638349514)

Unable to init server: Could not connect: Connection refused

(object_server3.py:520): Gdk-CRITICAL **: 05:49:09.687: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
/root/vrx_ws/src/usyd_vrx/usyd_vrx_vision/src/perception_task_submission.py:3: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
[ INFO] [1649828949.418136288]: Waiting for valid clock time...
[ INFO] [1649828949.552628439, 5.112000000]: Valid clock time received. Starting node.
[ INFO] [1649828949.568177882, 5.126000000]: Datum (latitude, longitude, altitude) is (-33.722562, 150.670000, 0.000000)
[ INFO] [1649828949.568203922, 5.126000000]: Datum UTM coordinate is (284109.543449, 6266167.257270) zone 56
[ INFO] [1649828949.568232554, 5.126000000]: Initial odometry pose is Origin: (0 0 0)
Rotation (RPY): (0, -0, 0)

[ INFO] [1649828949.590071312, 5.148000000]: Corrected for magnetic declination of 0.000000, user-specified offset of 0.000000 and meridian convergence of 0.022585. Transform heading factor is now 0.022585
[ INFO] [1649828949.590099734, 5.148000000]: Transform world frame pose is: Origin: (0 0 0)
Rotation (RPY): (0, -0, 0)

[ INFO] [1649828949.590113816, 5.148000000]: World frame->cartesian transform is Origin: (-425549.27741587883793 -6258152.9336737161502 0)
Rotation (RPY): (0, 0, -0.022585452840638349514)

... logging to /root/.ros/log/6b518108-baed-11ec-953c-0242ac100016/roslaunch-74fd88827efa-298.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://172.16.0.20:35403/

SUMMARY
========

PARAMETERS
 * /laserscan_multi_merger/angle_increment: 0.005
 * /laserscan_multi_merger/angle_max: 10
 * /laserscan_multi_merger/angle_min: -10
 * /laserscan_multi_merger/cloud_destination_topic: /wamv/sensors/lid...
 * /laserscan_multi_merger/destination_frame: wamv/base_link
 * /laserscan_multi_merger/laserscan_topics: /wamv/sensors/lid...
 * /laserscan_multi_merger/range_max: 500.0
 * /laserscan_multi_merger/range_min: 0.45
 * /laserscan_multi_merger/scan_destination_topic: /wamv/sensors/lid...
 * /laserscan_multi_merger/scan_time: 0.3333333
 * /map_server/frame_id: map
 * /mapping/clr_range: 3
 * /mapping/decrement: 2
 * /mapping/increment: 8
 * /mapping/min_range: 10
 * /mapping/offset_x: 400.0
 * /mapping/offset_y: 100.0
 * /mapping/resolution: 0.4
 * /mapping/width: 1024
 * /pointcloud_to_laserscan_lidar_wamv_back/angle_increment: 0.0087
 * /pointcloud_to_laserscan_lidar_wamv_back/angle_max: 1.5708
 * /pointcloud_to_laserscan_lidar_wamv_back/angle_min: -1.5708
 * /pointcloud_to_laserscan_lidar_wamv_back/concurrency_level: 1
 * /pointcloud_to_laserscan_lidar_wamv_back/max_height: 1.0
 * /pointcloud_to_laserscan_lidar_wamv_back/min_height: -3.0
 * /pointcloud_to_laserscan_lidar_wamv_back/range_max: 200
 * /pointcloud_to_laserscan_lidar_wamv_back/range_min: 2
 * /pointcloud_to_laserscan_lidar_wamv_back/scan_time: 0.3333
 * /pointcloud_to_laserscan_lidar_wamv_back/target_frame: wamv/lidar_wamv_b...
 * /pointcloud_to_laserscan_lidar_wamv_back/transform_tolerance: 0.01
 * /pointcloud_to_laserscan_lidar_wamv_back/use_inf: True
 * /pointcloud_to_laserscan_lidar_wamv_front/angle_increment: 0.0087
 * /pointcloud_to_laserscan_lidar_wamv_front/angle_max: 1.5708
 * /pointcloud_to_laserscan_lidar_wamv_front/angle_min: -1.5708
 * /pointcloud_to_laserscan_lidar_wamv_front/concurrency_level: 1
 * /pointcloud_to_laserscan_lidar_wamv_front/max_height: 1.0
 * /pointcloud_to_laserscan_lidar_wamv_front/min_height: -3.0
 * /pointcloud_to_laserscan_lidar_wamv_front/range_max: 200
 * /pointcloud_to_laserscan_lidar_wamv_front/range_min: 2
 * /pointcloud_to_laserscan_lidar_wamv_front/scan_time: 0.3333
 * /pointcloud_to_laserscan_lidar_wamv_front/target_frame: wamv/lidar_wamv_f...
 * /pointcloud_to_laserscan_lidar_wamv_front/transform_tolerance: 0.01
 * /pointcloud_to_laserscan_lidar_wamv_front/use_inf: True
 * /rosdistro: noetic
 * /rosversion: 1.15.14
 * /silent_tf_failure: True
 * /wamv/joint_state_publisher/gui: False
 * /wamv/joint_state_publisher/rate: 30
 * /wamv/joint_state_publisher/source_list: ['/wamv/joint_sta...
 * /wamv/robot_localization/ekf_localization/base_link_frame: wamv/base_link
 * /wamv/robot_localization/ekf_localization/frequency: 60
 * /wamv/robot_localization/ekf_localization/imu0: /wamv/sensors/imu...
 * /wamv/robot_localization/ekf_localization/imu0_config: [False, False, Fa...
 * /wamv/robot_localization/ekf_localization/imu0_differential: False
 * /wamv/robot_localization/ekf_localization/imu0_remove_gravitational_acceleration: True
 * /wamv/robot_localization/ekf_localization/map_frame: map
 * /wamv/robot_localization/ekf_localization/odom0: /wamv/robot_local...
 * /wamv/robot_localization/ekf_localization/odom0_config: [True, True, True...
 * /wamv/robot_localization/ekf_localization/odom0_differential: False
 * /wamv/robot_localization/ekf_localization/odom_frame: wamv/odom
 * /wamv/robot_localization/ekf_localization/publish_tf: True
 * /wamv/robot_localization/ekf_localization/sensor_timeout: 2.0
 * /wamv/robot_localization/ekf_localization/smooth_lagged_data: True
 * /wamv/robot_localization/ekf_localization/transform_time_offset: 0.1
 * /wamv/robot_localization/ekf_localization/two_d_mode: False
 * /wamv/robot_localization/ekf_localization/world_frame: wamv/odom
 * /wamv/robot_localization/navsat_transform_node/broadcast_utm_transform: True
 * /wamv/robot_localization/navsat_transform_node/datum: [-33.7225619, 150...
 * /wamv/robot_localization/navsat_transform_node/frequency: 60
 * /wamv/robot_localization/navsat_transform_node/magnetic_declination_radians: 0
 * /wamv/robot_localization/navsat_transform_node/publish_filtered_gps: True
 * /wamv/robot_localization/navsat_transform_node/tf_prefix: wamv
 * /wamv/robot_localization/navsat_transform_node/use_odometry_yaw: True
 * /wamv/robot_localization/navsat_transform_node/wait_for_datum: True
 * /wamv/robot_localization/navsat_transform_node/yaw_offset: 0

NODES
  /
    laserscan_multi_merger (ira_laser_tools/laserscan_multi_merger)
    map_server (map_server/map_server)
    map_tf_static (tf/static_transform_publisher)
    mapping (usyd_vrx_navigation/mapping)
    object_server (usyd_vrx_navigation/object_server3.py)
    object_visualiser (usyd_vrx_navigation/object_to_visualisation.py)
    perception_solution (usyd_vrx_vision/perception_task_submission.py)
    pointcloud_to_laserscan_lidar_wamv_back (pointcloud_to_laserscan/pointcloud_to_laserscan_node)
    pointcloud_to_laserscan_lidar_wamv_front (pointcloud_to_laserscan/pointcloud_to_laserscan_node)
  /wamv/
    joint_state_publisher (joint_state_publisher/joint_state_publisher)
    joint_states_relay (topic_tools/relay)
    odom_relay (topic_tools/relay)
    path_follower (usyd_vrx_control/path_follower.py)
    pos_to_twist (usyd_vrx_control/cmd_pos_to_cmd_vel.py)
    reset_object (usyd_vrx_vision/reset_pub.py)
    rob_st_pub (robot_state_publisher/robot_state_publisher)
    twist_control (usyd_vrx_control/twist_control_node.py)
  /wamv/robot_localization/
    ekf_localization (robot_localization/ekf_localization_node)
    navsat_transform_node (robot_localization/navsat_transform_node)

ROS_MASTER_URI=http://172.16.0.22:11311

process[wamv/joint_states_relay-1]: started with pid [363]
process[wamv/joint_state_publisher-2]: started with pid [364]
process[wamv/reset_object-3]: started with pid [365]
process[wamv/rob_st_pub-4]: started with pid [366]
process[wamv/robot_localization/ekf_localization-5]: started with pid [370]
process[wamv/robot_localization/navsat_transform_node-6]: started with pid [372]
process[wamv/odom_relay-7]: started with pid [373]
process[map_tf_static-8]: started with pid [380]
process[wamv/twist_control-9]: started with pid [387]
process[wamv/pos_to_twist-10]: started with pid [410]
process[wamv/path_follower-11]: started with pid [415]
process[map_server-12]: started with pid [417]
process[pointcloud_to_laserscan_lidar_wamv_front-13]: started with pid [418]
process[pointcloud_to_laserscan_lidar_wamv_back-14]: started with pid [435]
process[laserscan_multi_merger-15]: started with pid [457]
process[mapping-16]: started with pid [462]
process[object_server-17]: started with pid [520]
process[object_visualiser-18]: started with pid [521]
process[perception_solution-19]: started with pid [542]
[wamv/rob_st_pub-4] process has finished cleanly
log file: /root/.ros/log/6b518108-baed-11ec-953c-0242ac100016/wamv-rob_st_pub-4*.log
[map_tf_static-8] process has finished cleanly
log file: /root/.ros/log/6b518108-baed-11ec-953c-0242ac100016/map_tf_static-8*.log
[wamv/robot_localization/navsat_transform_node-6] process has finished cleanly
log file: /root/.ros/log/6b518108-baed-11ec-953c-0242ac100016/wamv-robot_localization-navsat_transform_node-6*.log
[wamv/robot_localization/navsat_transform_node-6] restarting process
process[wamv/robot_localization/navsat_transform_node-6]: started with pid [670]
shutdown request: [/wamv/joint_state_publisher] Reason: new node registered with same name
shutdown request: [/wamv/twist_control] Reason: new node registered with same name
shutdown request: [/wamv/path_follower] Reason: new node registered with same name
[ WARN] [1649828949.973801038]: Shutdown request received.
[ WARN] [1649828949.973845744]: Reason given for shutdown: [[/wamv/robot_localization/navsat_transform_node] Reason: new node registered with same name]
[ INFO] [1649828949.792540197]: Waiting for valid clock time...
shutdown request: [/wamv/pos_to_twist] Reason: new node registered with same name
[ WARN] [1649828950.098596354, 5.658000000]: navsat_transform, Parameter 'broadcast_utm_transform' has been deprecated. Please use'broadcast_cartesian_transform' instead.
[ WARN] [1649828950.131480323, 5.690000000]: Shutdown request received.
[ WARN] [1649828950.131590269, 5.691000000]: Reason given for shutdown: [[/wamv/robot_localization/navsat_transform_node] Reason: new node registered with same name]
[ WARN] [1649828950.155510704]: Shutdown request received.
[ WARN] [1649828950.155542467]: Reason given for shutdown: [[/wamv/robot_localization/navsat_transform_node] Reason: new node registered with same name]
[ WARN] [1649828950.173704539]: Shutdown request received.
[ WARN] [1649828950.173738804]: Reason given for shutdown: [[/wamv/robot_localization/navsat_transform_node] Reason: new node registered with same name]
[ INFO] [1649828949.814080246]: Waiting for valid clock time...
[ INFO] [1649828950.094100071, 5.653000000]: Valid clock time received. Starting node.
[ INFO] [1649828950.101019286, 5.660000000]: Datum (latitude, longitude, altitude) is (-33.722562, 150.670000, 0.000000)
[ INFO] [1649828950.101037496, 5.660000000]: Datum UTM coordinate is (284109.543449, 6266167.257270) zone 56
[ INFO] [1649828950.101059576, 5.660000000]: Initial odometry pose is Origin: (0 0 0)
Rotation (RPY): (0, -0, 0)

[ INFO] [1649828950.124596560, 5.684000000]: Corrected for magnetic declination of 0.000000, user-specified offset of 0.000000 and meridian convergence of 0.022585. Transform heading factor is now 0.022585
[ INFO] [1649828950.124639838, 5.684000000]: Transform world frame pose is: Origin: (0 0 0)
Rotation (RPY): (0, -0, 0)

[ INFO] [1649828950.124662087, 5.684000000]: World frame->cartesian transform is Origin: (-425549.27741587883793 -6258152.9336737161502 0)
Rotation (RPY): (0, 0, -0.022585452840638349514)

Traceback (most recent call last):
  File "/root/vrx_ws/src/usyd_vrx/usyd_vrx_control/src/path_follower.py", line 120, in <module>
    pf.control_desired_pose_loop()
  File "/root/vrx_ws/src/usyd_vrx/usyd_vrx_control/src/path_follower.py", line 71, in control_desired_pose_loop
    r.sleep()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/timer.py", line 103, in sleep
    sleep(self._remaining(curr_time))
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/timer.py", line 165, in sleep
    raise rospy.exceptions.ROSInterruptException("ROS shutdown request")
rospy.exceptions.ROSInterruptException: ROS shutdown request
Traceback (most recent call last):
  File "/root/vrx_ws/src/usyd_vrx/usyd_vrx_control/src/twist_control_node.py", line 210, in <module>
    a = WAMVController()
  File "/root/vrx_ws/src/usyd_vrx/usyd_vrx_control/src/twist_control_node.py", line 107, in __init__
    self.angular_controller()
  File "/root/vrx_ws/src/usyd_vrx/usyd_vrx_control/src/twist_control_node.py", line 202, in angular_controller
    r.sleep()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/timer.py", line 103, in sleep
    sleep(self._remaining(curr_time))
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/timer.py", line 165, in sleep
    raise rospy.exceptions.ROSInterruptException("ROS shutdown request")
rospy.exceptions.ROSInterruptException: ROS shutdown request
Traceback (most recent call last):
  File "/root/vrx_ws/src/usyd_vrx/usyd_vrx_control/src/cmd_pos_to_cmd_vel.py", line 210, in <module>
    pc.position_control_loop()
  File "/root/vrx_ws/src/usyd_vrx/usyd_vrx_control/src/cmd_pos_to_cmd_vel.py", line 91, in position_control_loop
    r.sleep()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/timer.py", line 103, in sleep
    sleep(self._remaining(curr_time))
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/timer.py", line 165, in sleep
    raise rospy.exceptions.ROSInterruptException("ROS shutdown request")
rospy.exceptions.ROSInterruptException: ROS shutdown request


```

**Comment by M1chaelM** [comment]
@JohnSumskas Are you planning to submit an update or would like us to merge this? We can leave it open until the deadline tonight if needed.

**Comment by JohnSumskas** [comment]
Oh wait I thought the dealine was 7 hours ago? When is the deadline?

**Comment by j-herman** [comment]
@JohnSumskas Corrections can be submitted until midnight tonight, Pacific time (https://github.com/osrf/vrx/wiki/vrx_2022-phase3_challenge)

**Comment by JohnSumskas** [comment]
Ok I will attempt to submit a correction by then. Thanks!

**Comment by JohnSumskas** [comment]
I have updated a correction to our image perception should launch correctly. 

Thanks for the feedback and help!

**Comment by M1chaelM** [comment]
Great! I'm now seeing messages published to /vrx/perception/landmark so it looks like there is activity on all tasks. I'm going to merge. After tonight we'll run and score the competition and the results will be announced at the awards party on 4/22 (as well as on the website). Good luck!

**Pull request merged**
