### PR TITLE
2022 rehearsal team itu asteam

### PR DESCRIPTION
**Pull request by otonomteknetakimi**
ITUASTEAM vrx final comment and push

### CODE REVIEW

**Review by caguero — CHANGES_REQUESTED** [review]
Thanks for your submission!

* [x] Compliance tests for component and propulsion configurations passed.
* [x] Successfully able to access Docker image.

Verified that the WAMV is active in the following tasks:
* [ ] Stationkeeping

I don't see any activity in your WAM-V during the station keeping task.

**Comment by otonomteknetakimi** [comment]
Yes, although loading workspace to docker our vehicle not move as we expect. Also team sent mail about this problem.

**Comment by otonomteknetakimi** [comment]
We expected to stationkeeping, wayfinding and perception tasks work. In Our local station launch files worked well which minimized the errors.

**Comment by M1chaelM** [comment]
Hi! Digging into this a little, it looks like you created your Docker image using the interactive option here: https://github.com/osrf/vrx/wiki/tutorials-vrx_docker_interactive

However, the image you submitted does not have a lot of customization. It looks just like you followed the tutorial to create a minimal working image. You followed it correctly, but the resulting image is _minimal_ in the sense that it doesn't do anything other than drive straight ahead. In this case, it doesn't even do that because you're using a different thruster configuration. 

More specifically, when the image is executed it runs the `/ros_entrypoint.sh` script, which sources the generic `ros` environment and then calls `run_my_system.bash`.

The `run_my_system.bash` script has not been modified so it just echos "sending forward command" and then tries to drive the WAMV forward using:
```
# Send forward command
RATE=1
CMD=2
echo "Sending forward command"
rostopic pub /wamv/thrusters/left_thrust_cmd std_msgs/Float32 -r ${RATE} -- ${CMD} &
rostopic pub /wamv/thrusters/right_thrust_cmd std_msgs/Float32 -r ${RATE} -- ${CMD}
```
However, the `rostopic pub` commands have no effect because you are using a holonomic thruster configuration, so the topic names are wrong.

### How to fix

To get this to work, you would need to modify the `run_my_system.bash` script so it sources your workspace and runs the appropriate commands for the task you are trying to solve. This means you also need some code to detect which task is running.

In addition, it's likely that you need to build your workspace in the image, rather than building it on your local machine and copying it in. This is because ROS workspaces don't expect to be moved around. One way to fix this would be to log in to the image, delete the `devel` and `build` folders and build again. However, when you do this it's likely you will also need to install dependencies on the image so the build can complete. Once you have built successfully, you would use `docker commit` to make the changes persistent, and then push the new version to the repository.

I hope this helps! My guess is that it will take some effort to fix this problem, but I don't think it's insurmountable. The deadline for corrections is tonight at 11:59PM PT. Please let us know if/when you'd like us to test again.

**Comment by otonomteknetakimi** [comment]
We apply the solutions that you described for our issues. We build the workspace on the docker image and cp our scripts only. After that we add some code to detect which task is running. Could you please check and test. Because of the time differences we saw the your answer lately. Then quickly apply solutions.
Thank you for your valuable effort.
Kindest regards.

**Comment by caguero** [comment]
I tried your recent version but unfortunately your WAM-V doesn't show any activity in the station keeping task. This is the error I see in the terminal:

```
python3: can't open file 'stationkeeping.py': [Errno 2] No such file or directory
```

**Comment by otonomteknetakimi** [comment]
How can we check files in image , because we uploaded stationkeeping.py. But this error seems.

**Comment by M1chaelM** [comment]
> How can we check files in image , because we uploaded stationkeeping.py. But this error seems.

For the quickest resolution, please take a look at the [Docker image troubleshooting tutorials](https://github.com/osrf/vrx/wiki/tutorials-vrx_docker_troubleshooting).

In particular, you may want to follow the tutorial for [running your container manually](https://github.com/osrf/vrx/wiki/tutorials-vrx_docker_manual_run) so you can see where your files are. Guessing from the error message, it is likely that the path is wrong.

**Comment by otonomteknetakimi** [comment]
We fixed the path problem and try the test but this time vehicle do not move. Same codes are workin in our local workspace.

**Comment by M1chaelM** [comment]
OK, let me take a look.

**Comment by M1chaelM** [comment]
Following the steps described in the tutorial on [getting basic debugging info](https://github.com/osrf/vrx/wiki/tutorials-vrx_docker_debug_info) and running `docker ps -a` I can see that your container's entrypoint is set to `bash` instead of the expected `/ros_entrypoint.sh`:
```
CONTAINER ID   IMAGE                                    COMMAND                  CREATED              STATUS                          PORTS       NAMES
f51ea7b3db23   ituasteam/vrx-competitor-2022:v2.2022    "bash"                   About a minute ago   Exited (0) About a minute ago               vrx-competitor-system
```
So, it's not surprising that this doesn't run because it isn't configured to call anything. To fix this, run `docker ps -a` to get your container ID, then run:
```
docker commit --change='ENTRYPOINT ["/ros_entrypoint.sh"]' <YOUR_CONTAINER_ID> ituasteam/vrx-competitor-2022:v3.2022
docker push ituasteam/vrx-competitor-2022:v3.2022
```

**Comment by M1chaelM** [comment]
Once the above error is fixed, you have additional path errors in `Listener_task.py`. The problem is that because of the way you are calling the script, your working directory is not where you are expecting it to be. One way to correct these errors is to just use the absolute paths:
```
extProc = sp.Popen(['python3','/root/vrx_ws/src/vrx/vrx_gazebo/scripts/stationkeeping.py'])
```
If I fix these paths and test your image, you no longer get file not found messages. Instead, I see output that looks like:
```
['station_keeping']
[True]
['station_keeping']
[False]
['station_keeping']
[False]
```
The first message is `True` and after that there are hundreds of repeating messages with `False` in the brackets.

**Comment by otonomteknetakimi** [comment]
We apply things which you describe about solve the problem. When first true returning it s mean that stationkeeping running and our solving algorithm which stationkeeping.py file is running while task situation return to the finished. So we expect that but again vehicle not working as in our local workspace.

**Comment by otonomteknetakimi** [comment]
We think that problem about the  not working our launch file because for example we include the localization package in it so while did not work robot_localization rospy.wait for message does not allow the work code. Because topics are not publishing. How can include it in bash file ?

**Comment by otonomteknetakimi** [comment]
We add rosrun commands for require nodes and roslaunch for needed launch file in bash file.

**Comment by M1chaelM** [comment]
Yes, I agree. It looks like you are stuck waiting on `robot_localization` messages, but `robot_localization` is not running. If your Python script relies on this, you could launch it in the background in `run_my_system.bash` before you run `Listener_task.py`. To launch something in the background you just put a "&" at the end of the command.

**Comment by M1chaelM** [comment]
> We add rosrun commands for require nodes and roslaunch for needed launch file in bash file.

Ah, ok. I'll pull the new version.

**Comment by M1chaelM** [comment]
I think you will need to use the "&" to run your tasks in the background. Otherwise the script will wait for the command to end before it runs the next one, and your code will never execute.

When I fix this I get the following error message from your joint state publisher:
```
rosmaster already setup
[ERROR] [1649978416.001103137]: Could not find parameter robot_description on parameter server
[ WARN] [1649978416.420768607, 4.166000000]: Failed to meet update rate! Took 4.1660000000000003695
[ WARN] [1649978416.421571562, 4.167000000]: Failed to meet update rate! Took 4.1503333329999998469
[ WARN] [1649978416.424885496, 4.170000000]: navsat_transform, Parameter 'broadcast_utm_transform' has been deprecated. Please use'broadcast_cartesian_transform' instead.
Traceback (most recent call last):
  File "/root/vrx_ws/devel/lib/joint_state_publisher/joint_state_publisher", line 15, in <module>
    exec(compile(fh.read(), python_script, 'exec'), context)
  File "/root/vrx_ws/src/joint_state_publisher/joint_state_publisher/scripts/joint_state_publisher", line 42, in <module>
    jsp = joint_state_publisher.JointStatePublisher()
  File "<string>", line 145, in __init__
RuntimeError: The robot_description parameter is required and not set.
```

**Comment by otonomteknetakimi** [comment]
Yes, after i saw your advice & i add them after that i realize that add one parameters for joint state, how can i add param in bash file ?

**Comment by M1chaelM** [comment]
> Yes, after i saw your advice & i add them after that i realize that add one parameters for joint state, how can i add param in bash file ?

It should be the same syntax you use when calling on the command line. The bash file works just like a list of bash commands run one after another. Sorry if I'm misunderstanding your question--please let me know if that makes sense.

**Comment by otonomteknetakimi** [comment]
Normally in my launch file describe that in jonit state node, param gui = false so i try to in bash file rosparam set gui flase, is this wrong ?

**Comment by M1chaelM** [comment]
> Normally in my launch file describe that in jonit state node, param gui = false so i try to in bash file rosparam set gui flase, is this wrong ?

Could you post the launch file you're using?

**Comment by otonomteknetakimi** [comment]
`  
  <arg name="extra_gazebo_args" default=""/>
  
  <arg name="namespace" default="wamv"/>

  
  <arg name="x" default="-532" />
  <arg name="y" default="162" />
  <arg name="z" default="0.1" />
  <arg name="P" default="0" />
  <arg name="R" default="0" />
  <arg name="Y" default="1" />

  
  <arg name="thrust_config" default="X" />

  
  <arg name="wamv_locked" default="true" />

  
  <arg name="vrx_sensors_enabled" default="true" />

  
  <include file="$(find gazebo_ros)/launch/empty_world.launch">
    <arg name="world_name" value="$(arg world)"/>
    <arg name="verbose" value="$(arg verbose)"/>
    <arg name="paused" value="$(arg paused)"/>
    <arg name="use_sim_time" value="true"/>
    <arg name="gui" value="$(arg gui)" />
    <arg name="extra_gazebo_args" value="$(arg extra_gazebo_args)"/>
  </include>

   
  <arg name="urdf" default="$(find wamv_gazebo)/urdf/wamv_gazebo.urdf.xacro"/>
  <param name="$(arg namespace)/robot_description"
         command="$(find xacro)/xacro &#x002D;&#x002D;inorder '$(arg urdf)'
         locked:=$(arg wamv_locked)
         thruster_config:=$(arg thrust_config)
         vrx_sensors_enabled:=$(arg vrx_sensors_enabled)
         namespace:=$(arg namespace) "/>

  
  <node name="spawn_model" pkg="gazebo_ros" type="spawn_model"
        args="-x $(arg x) -y $(arg y) -z $(arg z)
              -R $(arg R) -P $(arg P) -Y $(arg Y)
              -urdf -param $(arg namespace)/robot_description -model wamv "/>
  <param name="use_sim_time" value="false"/>
  <include file="$(find vrx_gazebo)/launch/localization.launch" />
  <node name="pinger_visualization" pkg="vrx_gazebo" type="pinger_visualization.py" />
  

    
  <node ns="wamv" pkg="robot_state_publisher" type="robot_state_publisher" name="rob_st_pub"/>
  
    
  <node ns="wamv" pkg="joint_state_publisher" type="joint_state_publisher" name="joint_state_publisher">
   	<param name="gui" value="false" />

  </node>
  
  <arg name="rviz_config" default="$(find wamv_gazebo)/config/rviz_vrx.rviz" />
  <node pkg="rviz" type="rviz"
        name="wamv_visualization" args="-d $(arg rviz_config)" />

</launch>`

**Comment by otonomteknetakimi** [comment]
`
  <arg name="extra_gazebo_args" default=""/>
  
  <arg name="namespace" default="wamv"/>

  
  <arg name="x" default="-532" />
  <arg name="y" default="162" />
  <arg name="z" default="0.1" />
  <arg name="P" default="0" />
  <arg name="R" default="0" />
  <arg name="Y" default="1" />

  
  <arg name="thrust_config" default="X" />

  
  <arg name="wamv_locked" default="true" />

  
  <arg name="vrx_sensors_enabled" default="true" />

  
  <include file="$(find gazebo_ros)/launch/empty_world.launch">
    <arg name="world_name" value="$(arg world)"/>
    <arg name="verbose" value="$(arg verbose)"/>
    <arg name="paused" value="$(arg paused)"/>
    <arg name="use_sim_time" value="true"/>
    <arg name="gui" value="$(arg gui)" />
    <arg name="extra_gazebo_args" value="$(arg extra_gazebo_args)"/>
  </include>

   
  <arg name="urdf" default="$(find wamv_gazebo)/urdf/wamv_gazebo.urdf.xacro"/>
  <param name="$(arg namespace)/robot_description"
         command="$(find xacro)/xacro &#x002D;&#x002D;inorder '$(arg urdf)'
         locked:=$(arg wamv_locked)
         thruster_config:=$(arg thrust_config)
         vrx_sensors_enabled:=$(arg vrx_sensors_enabled)
         namespace:=$(arg namespace) "/>

  
  <node name="spawn_model" pkg="gazebo_ros" type="spawn_model"
        args="-x $(arg x) -y $(arg y) -z $(arg z)
              -R $(arg R) -P $(arg P) -Y $(arg Y)
              -urdf -param $(arg namespace)/robot_description -model wamv "/>
  <param name="use_sim_time" value="false"/>
  <include file="$(find vrx_gazebo)/launch/localization.launch" />
  <node name="pinger_visualization" pkg="vrx_gazebo" type="pinger_visualization.py" />
  

    
  <node ns="wamv" pkg="robot_state_publisher" type="robot_state_publisher" name="rob_st_pub"/>
  
    
  <node ns="wamv" pkg="joint_state_publisher" type="joint_state_publisher" name="joint_state_publisher">
   	<param name="gui" value="false" />

  </node>
  
  <arg name="rviz_config" default="$(find wamv_gazebo)/config/rviz_vrx.rviz" />
  <node pkg="rviz" type="rviz"
        name="wamv_visualization" args="-d $(arg rviz_config)" />

</launch>
`

**Comment by otonomteknetakimi** [comment]
<launch>
<env name="ROSCONSOLE_CONFIG_FILE" value="$(find vrx_gazebo)/config/custom_rosconsole.conf"/>

<arg name="world" default="$(find vrx_gazebo)/worlds/stationkeeping_task.world"/>

<arg name="gui" default="true"/>

<arg name="verbose" default="false"/>

<arg name="paused" default="false"/>

<arg name="extra_gazebo_args" default=""/>

<arg name="namespace" default="wamv"/>

<arg name="x" default="-532"/>
<arg name="y" default="162"/>
<arg name="z" default="0.1"/>
<arg name="P" default="0"/>
<arg name="R" default="0"/>
<arg name="Y" default="1"/>

<arg name="thrust_config" default="X"/>

<arg name="wamv_locked" default="true"/>

<arg name="vrx_sensors_enabled" default="true"/>

<include file="$(find gazebo_ros)/launch/empty_world.launch">
<arg name="world_name" value="$(arg world)"/>
<arg name="verbose" value="$(arg verbose)"/>
<arg name="paused" value="$(arg paused)"/>
<arg name="use_sim_time" value="true"/>
<arg name="gui" value="$(arg gui)"/>
<arg name="extra_gazebo_args" value="$(arg extra_gazebo_args)"/>
</include>

<arg name="urdf" default="$(find wamv_gazebo)/urdf/wamv_gazebo.urdf.xacro"/>
<param name="$(arg namespace)/robot_description" command="$(find xacro)/xacro --inorder '$(arg urdf)' locked:=$(arg wamv_locked) thruster_config:=$(arg thrust_config) vrx_sensors_enabled:=$(arg vrx_sensors_enabled) namespace:=$(arg namespace) "/>

<node name="spawn_model" pkg="gazebo_ros" type="spawn_model" args="-x $(arg x) -y $(arg y) -z $(arg z) -R $(arg R) -P $(arg P) -Y $(arg Y) -urdf -param $(arg namespace)/robot_description -model wamv "/>
<param name="use_sim_time" value="false"/>
<include file="$(find vrx_gazebo)/launch/localization.launch"/>
<node name="pinger_visualization" pkg="vrx_gazebo" type="pinger_visualization.py"/>


<node ns="wamv" pkg="robot_state_publisher" type="robot_state_publisher" name="rob_st_pub"/>

<node ns="wamv" pkg="joint_state_publisher" type="joint_state_publisher" name="joint_state_publisher">
<param name="gui" value="false"/>
</node>
<arg name="rviz_config" default="$(find wamv_gazebo)/config/rviz_vrx.rviz"/>
<node pkg="rviz" type="rviz" name="wamv_visualization" args="-d $(arg rviz_config)"/>
</launch>

**Comment by M1chaelM** [comment]
It looks like there may be some problem posting the file. In case it saves you some trouble: if you are using a launch file locally, can you just use the launch file in your Docker container also?

**Comment by otonomteknetakimi** [comment]
stationkeeping

**Comment by otonomteknetakimi** [comment]
Okay , i am trying to do.

**Comment by otonomteknetakimi** [comment]
Finally, it works. Could you check it please ?
Thanks for your very valuable efforts.

**Comment by otonomteknetakimi** [comment]
I guess only have a problem about perception task.

**Comment by otonomteknetakimi** [comment]
qt.qpa.xcb: could not connect to display 
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, xcb.

is the our error message, we use yolo and pytorch for this project. Could you give advice about that ?

**Comment by otonomteknetakimi** [comment]
Now, it seems that working. Can you let me know if there is any problem about stationkeeping, wayfinding and perception ?

**Comment by M1chaelM** [comment]
Sure, no problem. Right now I see promising activity in stationkeeping and wayfinding, and perception seems to be doing something. However, it looks like no messages are being published to `/vrx/perception/landmark`.

I'm happy to keep checking on this, but since we are considerably past the deadline we will need to annotate this submission as coming in late. I think we can still score it along with the rest of the results so you can see where you rank--just wanted to explain how it will be handled.

**Comment by otonomteknetakimi** [comment]
Okay, thanks for your support and understanding.

**Comment by M1chaelM** [comment]
Do you want to make any further changes to try to fix the perception task? Or would you like me to merge this?

**Comment by otonomteknetakimi** [comment]
We will not make any changes. Thank you for your valuable effort and understanding

**Comment by M1chaelM** [comment]
OK, thank you for this submission! I will merge it. Over the next week we will run the competition and tally the scores. Then we'll announce the results at the virtual awards party on 4/22 (and also post them online).

**Pull request merged**
