### PR TITLE
Team AMORE submission for 2022/phase3 rehearsal event.

### PR DESCRIPTION
**Pull request by lssuamore**

### CODE REVIEW

**Comment by M1chaelM** [comment]
Per our email exchange, this solution is expected to work on tasks 1-3.

**Comment by M1chaelM** [comment]
When I attempt to run a trial I get the following error:
```
RLException: [VRX_AMORE.launch] is neither a launch file in package [amore] nor is [amore] a launch file name
The traceback for the exception was written to the log file
```
Have you tried running a trial locally? We have a tutorial for this that might help you: https://github.com/osrf/vrx/wiki/vrx_2022-testing

There is also a new sequence of troubleshooting tutorials here: https://github.com/osrf/vrx/wiki/tutorials-vrx_docker_troubleshooting

**Comment by M1chaelM** [comment]
I ran your container manually following a process similar to what is described here: https://github.com/osrf/vrx/wiki/tutorials-vrx_docker_manual_run

It looks like your `run_my_system.bash` script has this line
```
source "/root/RobotX2022/devel/setup.bash"
```
However, the actual directory is stored at
```
/RobotX2022/devel/setup.bash
```
So I think your `setup.bash` is not getting sourced, but this should be an easy fix.

**Comment by lssuamore** [comment]
Michael, in order for us to edit the run_my_system.bash, we need to get back into our container and edit the bash correct? What are the commands I need to be able to run and get into my container, so that I can edit the bash?

**Comment by M1chaelM** [comment]
> Michael, in order for us to edit the run_my_system.bash, we need to get back into our container and edit the bash correct? What are the commands I need to be able to run and get into my container, so that I can edit the bash?

There are a few ways to change the script. If you are using an interactive process to build your container (i.e. "option 1" described in [this tutorial](https://github.com/osrf/vrx/wiki/tutorials-vrx_docker_interactive)) then yes, one option is to run the container, edit the script, and commit the changes with `docker commit`. The command for opening a shell into your container is

```
docker run -it --entrypoint /bin/bash ${USERNAME}/${IMAGE_NAME}:${TAG}
```
A more complete explanation is given in the [troubleshooting tutorial for running your image manually](https://github.com/osrf/vrx/wiki/tutorials-vrx_docker_manual_run).

**Comment by lssuamore** [comment]
Hi Michael,
We changed our source in the run_my_system.bash. We went to run our docker image via the tutorial using vrx-docker server. While running the stationkeeping task replay there was no movement as well as the goal post didn't show up like it does when running locally. This also happened with the wayfinding replay as well. We did try to move our repository into the ~ directory and sourced it properly but still nothing. Is there a reason for this that you know of? We don't really know how to progress at this point.

**Comment by M1chaelM** [comment]
The wayfinding and stationkeeping visual markers do not appear in playback--this is the expected behavior. If you need to see them for some reason I suggest [running the trial manually as described in the tutorial here](https://github.com/osrf/vrx/wiki/tutorials-vrx_docker_manual_trial). This also has the advantage of giving you more options for debugging.

Generally, I highly recommend reading through the entire set of Docker tutorials for creating and troubleshooting your competitor Docker image: https://github.com/osrf/vrx/wiki/tutorials-vrx_competitor_image

When you say

> We did try to move our repository into the ~ directory and sourced it properly but still nothing.

I am not really sure what you did. Are you saying that instead of changing the line in `run_my_system.bash` that says:
```
source "/root/RobotX2022/devel/setup.bash"
```
you instead ran something like this:
```
docker run -it --entrypoint /bin/bash ${USERNAME}/${IMAGE_NAME}:${TAG}
mv /RobotX2022 /root
exit
docker commit -m "moved workspace to /root" -a ${AUTHOR_NAME} ${CONTAINER_ID} ${USERNAME}/${IMAGE_NAME}:${TAG}
docker push ${USERNAME}/${IMAGE_NAME}:${TAG}
```
If so that would fix your sourcing error but moving the workspace will break it unless you cleaned it out and rebuilt it. Also, in this case there would be no need to change the `run_my_system.bash` file since you moved the directory.

My suggestion instead would be to leave the `RobotX2022` directory where it is and just change the `source ` command to
```
source "/RobotX2022/devel/setup.bash"
```
You could do this by running:
```
docker run -it --entrypoint /bin/bash ${USERNAME}/${IMAGE_NAME}:${TAG}
nano run_my_system.bash
```
Then edit, save, and exit the file. Then run:
```
exit
docker commit -m "edited run_my_system.bash" -a ${AUTHOR_NAME} ${CONTAINER_ID} ${USERNAME}/${IMAGE_NAME}:${TAG}
docker push ${USERNAME}/${IMAGE_NAME}:${TAG}
```
Either way, if you succeed in modifying your image but are still having problems I'm happy to look at it. Just let me know where to find the new version.

**Comment by lssuamore** [comment]
We created a whole new image with our updated repository. We modified it exactly how you shown us above. The new image is named amore2122/amore_phase3_try:v2 . Can you take a look at it and make sure everything is correct now. We really appreciate all your help and patience.

**Comment by lssuamore** [comment]
The other issue we are having is when we run the local testing environment and follow this tutorial https://github.com/osrf/vrx/wiki/tutorials-vrx_docker_examine . We are not able to rostopic echo /vrx/task/info it asks if the messages are built. I think this is a big issue as if the message isn't there then our program won't run at all.

**Comment by M1chaelM** [comment]
> We created a whole new image with our updated repository. We modified it exactly how you shown us above. The new image is named amore2122/amore_phase3_try:v2 . Can you take a look at it and make sure everything is correct now. We really appreciate all your help and patience.

I'm taking a look now. Here is what I'm doing to test:
```
docker run -it amore2122/amore_phase3_try:v2
```
This pulls your image from the repository and runs it. However, instead of running an entrypoint script, it opens a bash shell. This is probably a problem. To confirm, I open a new terminal and run:
```
docker container ls
```
This shows
```
CONTAINER ID   IMAGE                           COMMAND       CREATED         STATUS         PORTS     NAMES
acba61c557bb   amore2122/amore_phase3_try:v2   "/bin/bash"   7 seconds ago   Up 6 seconds             optimistic_kepler
```
This shows that the entrypoint command is `/bin/bash`. We will need to fix this to get your container to run. To do this using the `docker commit` command, I exit the shell and run
```
docker commit --change='ENTRYPOINT ["/ros_entrypoint.sh"]' acba61c557bb amore2122/amore_phase3_try:v2
```
Where `acba61c557bb` is the container ID I got from the `docker container ls` command. Now rerunning:
```
docker run -it amore2122/amore_phase3_try:v2
```
shows that your image runs the entrypoint as expected and then produces a ton of activity, so I think it's definitely doing something. The next thing I will do is run a trial and see whether the WAMV moves.

**Comment by M1chaelM** [comment]
Next I'm going to test your image using the instructions here: https://github.com/osrf/vrx/wiki/vrx_2022-testing

For this to work on your machine, you would first need to make sure you push modified version of your image back up to the repository:
```
docker push amore2122/amore_phase3_try:v2
```
This is because the `run_trial.bash` script always tries to use whatever is stored in the remote repository and would overwrite any local changes that you haven't pushed. In my case I can't push to your repository so I will hack the script a bit instead.

While the trial is running, I opened an interactive bash session into your container to check on your question about the `/vrx/task/info` topic. This topic uses a custom `TASK` message, so if you try to echo it without sourcing a workspace that builds the message, you will get the error you described, and if you are not building the message anywhere on your container that could be a problem. Happily, when I run
```
source /opt/ros/noetic/setup.bash
source /vrx_amore/devel/setup.bash
rostopic echo /vrx/task/info 
```
I see the expected output, so you are building the messages when you build `vrx_amore`, and as long as your script is sourcing them properly, your system should be able to work with them.

As a side note, a lot of the problems you are running into are really problems relating to the way `bash` manages its runtime environment. In this case you are sourcing the environment in your script but when you open a new shell you have to start over. (Admittedly, working with Docker tends to really force this kind of issue to the front.)

**Comment by M1chaelM** [comment]
The good news is that your image is now not erroring out and it can communicate with the server, and it's definitely doing _something_. The bad news is that running the replay:
```
TASK=stationkeeping
TRIAL=0
./replay_trial.bash -n $TEAM $TASK $TRIAL
```
shows that your WAMV still doesn't move. I'm not sure why, so the next thing I'll do is [manually run the trial](https://github.com/osrf/vrx/wiki/tutorials-vrx_docker_manual_trial).

**Comment by M1chaelM** [comment]
When I manually run the trial, I'm seeing that your system appears to execute properly, but there is some error output. I'm not sure whether or not this is related to the WAMV not moving, but the 3 main kinds of messages that I see are as follows.

1. There is one error message early on that says:
  ```
  [perception_array-5] process has died [pid 387, exit code 1, cmd /vrx_amore/devel/lib/amore/perception_array __name:=perception_array __log:=/root/.ros/log/e4a13306-b5d3-11ec-b84c-0242ac100016/perception_array-5.log].
log file: /root/.ros/log/e4a13306-b5d3-11ec-b84c-0242ac100016/perception_array-5*.log
  ```
2. There are many many info messages that say:
  ```
  [ INFO] [1649268165.893992552, 79.961000000]: !mission_control_initialized --MC
  ```
3. There are intermittent warning messages that say:
  ```
  [ WARN] [1649268165.720776105, 79.789000000]: Haven't received Odometry on </nav_odom> for 1.0 seconds! Will not broadcast transform!
  ```

**Comment by M1chaelM** [comment]
If I open another terminal into your container during the trial, source your environment, and run

```
rostopic pub /wamv/thrusters/left_thrust_cmd std_msgs/Float32 -r ${RATE} -- ${CMD} &
```
I see the WAMV start to drive around in a circle as expected. So it seems to me that the remaining problems are somewhere in your code. Since your code is running locally, and it looks to me like the environment is now sourced correctly, I wonder if the container image might be missing some dependency you need.

I probably shouldn't dig too much deeper, but from a quick glance at your `mission_control.cpp` it looks like your mission control will not initialize unless your `perception_array_initialized` variable is set to true. So the crashing perception array seems to be preventing anything else from happening. Running the `perception_array` node manually during the trial gives the error:
```
Unable to init server: Could not connect: Connection refused

(Left Camera Updated:779): Gtk-WARNING **: 18:24:48.442: cannot open display: 
```
Again, I haven't looked too deep, but are you trying to produce some kind of graphical output as part of your perception processing routine?

**Comment by lssuamore** [comment]
Thank you for going through the whole process! The first error message you listed is an issue that currently has not been resolved. perception_array is our code that deals with the camera. The crashing of this code should not be the reason our robot is not moving. The second message you listed is expected. This message will appear until all the codes in the launch file have been initialized and communicated back to the state machine code. The last message you listed is also expected at the beginning of the launch because the systems are not yet initialized and thus not printing to </nav_odom>, which is a node we need to publish for geonav_transform package to function properly and convert spherical ECEF to ENU coordinates. Once the system becomes initialized, the propulsion_system should start and output a bunch of debug messages.

**Comment by lssuamore** [comment]
Yes, we were trying to output the camera view to the terminal window; however, this is unnecessary.

**Comment by M1chaelM** [comment]
Ah, OK. In that case, it sounds like what's really missing is the `propulsion_system`. I'm not sure why, but again I'd start with checking for missing dependencies. In case it's helpful, here is a little more output from when your launch file starts:

```
ROS_MASTER_URI=http://172.16.0.22:11311

process[geonav_transform_node-1]: started with pid [960]
process[navigation_array-2]: started with pid [961]
process[propulsion_system-3]: started with pid [962]
process[mission_control-4]: started with pid [963]
process[perception_array-5]: started with pid [970]
[ INFO] [1649270970.807714709]: Datum (latitude, longitude, altitude) is (-33.724223, 150.679736, 0.000000)
[ INFO] [1649270970.809434000]: Datum UTM Zone is: 56H
[ INFO] [1649270970.809455796]: Datum UTM coordinate is (285015.985823, 6266003.367264)
[ INFO] [1649270970.809497297]: Datum orientation roll, pitch, yaw is (0, -0, 0)
[ INFO] [1649270970.812331832]: !navigation_array_initialized -- NA
[ INFO] [1649270970.815535734]: !propulsion_system_initialized -- PS
[DEBUG] [1649270970.817158128]: Trying to publish message of type [std_msgs/Bool/8b94c1b53db61fb6aed406028ad6332a] on a publisher with type [std_msgs/Bool/8b94c1b53db61fb6aed406028ad6332a]
[DEBUG] [1649270970.817190114]: Trying to publish message of type [std_msgs/Float32/73fcbf46b49191e672908e50842a83d4] on a publisher with type [std_msgs/Float32/73fcbf46b49191e672908e50842a83d4]
[ INFO] [1649270970.822167230]: !mission_control_initialized --MC
[ INFO] [1649270970.832210744]: !mission_control_initialized --MC
[ INFO] [1649270970.842229541]: !mission_control_initialized --MC
[ INFO] [1649270970.852232485]: !mission_control_initialized --MC
Unable to init server: Could not connect: Connection refused

(Left Camera Updated:970): Gtk-WARNING **: 18:49:30.853: cannot open display: 
[ INFO] [1649270970.862209229]: !mission_control_initialized --MC

```

**Comment by M1chaelM** [comment]
Calling the `propulsion_system` directly during the trial gives:
```
[ INFO] [1649271265.412704768]: !propulsion_system_initialized -- PS
[DEBUG] [1649271265.413237490]: Trying to publish message of type [std_msgs/Bool/8b94c1b53db61fb6aed406028ad6332a] on a publisher with type [std_msgs/Bool/8b94c1b53db61fb6aed406028ad6332a]
[DEBUG] [1649271265.413263914]: Trying to publish message of type [std_msgs/Float32/73fcbf46b49191e672908e50842a83d4] on a publisher with type [std_msgs/Float32/73fcbf46b49191e672908e50842a83d4]
[ INFO] [1649271265.996651971, 23.116000000]: !propulsion_system_initialized -- PS
[ INFO] [1649271265.996721475, 23.116000000]: !propulsion_system_initialized -- PS
[ INFO] [1649271266.350394183, 23.450000000]: !propulsion_system_initialized -- PS
[ INFO] [1649271266.697030374, 23.783000000]: !propulsion_system_initialized -- PS
[ INFO] [1649271267.036008081, 24.116000000]: !propulsion_system_initialized -- PS
[ INFO] [1649271267.394944038, 24.450000000]: !propulsion_system_initialized -- PS
[ INFO] [1649271267.728643621, 24.783000000]: !propulsion_system_initialized -- PS
[ INFO] [1649271268.061224168, 25.116000000]: !propulsion_system_initialized -- PS
[ INFO] [1649271268.402133322, 25.450000000]: !propulsion_system_initialized -- PS
[ INFO] [1649271268.757173776, 25.783000000]: !propulsion_system_initialized -- PS
```
And then no further output.

**Comment by lssuamore** [comment]
Hmmm, I do not understand how the launch can all function locally, but not on the image. Propulsion_sysytem does not seem to be the issue to me because it launches with the launch: "process[propulsion_system-3]: started with pid [962]"

**Comment by M1chaelM** [comment]
> Hmmm, I do not understand how the launch can all function locally, but not on the image. Propulsion_sysytem does not seem to be the issue to me because it launches with the launch: "process[propulsion_system-3]: started with pid [962]"

There are many ways this can happen (just like when code runs on one machine but not another one), but the most common reason is that the image is missing some dependency that is installed on your local machine.

I'm just guessing what might be wrong with your code based on the error messages, so I think your assessment is probably better than mine if you think the `propulsion_system` is working correctly. It's definitely being started, and I don't see it crash, but your comment above made me think it should be producing debug messages. I'm not seeing any. After the initial output I post above I just see a repetition of those `INFO` and `WARN` messages until the trial ends.

**Comment by lssuamore** [comment]
Michael,
Thank you so much, because of your help we now have a working docker image. We look forward to submitting our final version on Tuesday.

**Comment by M1chaelM** [comment]
> Michael, Thank you so much, because of your help we now have a working docker image. We look forward to submitting our final version on Tuesday.

So glad to hear this! I'm going to close this PR and we'll look forward to your next one.

**Pull request closed without merging**
