### PR TITLE
BYU Team 2022 Rehearsal Event

### PR DESCRIPTION
**Pull request by Caden-Ellis77**
Let us know if you have any questions

### CODE REVIEW

**Comment by caguero** [comment]
Could you update the path where your file is located? It should be `2022/phase1_hello_world/<YOUR_TEAM_NAME>/video_link.txt `

**Review by caguero — CHANGES_REQUESTED** [review]
Thanks for the submission! Could you update the path where your file is located? It should be `2022/phase1_hello_world/<YOUR_TEAM_NAME>/video_link.txt `

**Comment by Caden-Ellis77** [comment]
I fixed it!

**Comment by M1chaelM** [comment]
Yours is fixed but I think you are now accidentally deleting our example_team submission...

**Review by caguero — CHANGES_REQUESTED** [review]
hi @Caden-Ellis77 . Do you think you could restore `example_team/video_link.txt`?

**Comment by Caden-Ellis77** [comment]
I created a new pull request. Is it acceptable?

**Comment by M1chaelM** [comment]
Closing this PR since we accepted PR #28 instead.

**Pull request closed without merging**
