### PR TITLE
2023 rehearsal and hello world GTMRG

### PR DESCRIPTION
**Pull request by gatechmrg**
This submission tackles tasks #1 and #2. All other tasks are not functional.

### CODE REVIEW

**Review by caguero — APPROVED** [review]
Thanks for your VRX submission!

* [x] Your video is reachable.
* [x] Compliance tests for component and propulsion configurations passed.
* [x] Successfully able to access Docker image.
* [x] Verified that the WAMV is active in the stationkeeping task.

All looking good!

**Review by caguero — CHANGES_REQUESTED** [review]
Minor changes:
  * No need to include `usv.urdf`
  * No need to include `video_link.txt` in the phase2 directory.

Could you update this PR with these changes please?

**Comment by caguero** [comment]
@gatechmrg , friendly ping.

**Review by caguero — APPROVED** [review]
I'm merging this PR because the extra files are harmless but consider the suggestion for phase 3.

**Comment by gatechmrg** [comment]
Apologies, this account isn't actively monitored. @seantfish and @mroglan are primary contacts.

**Pull request merged**
