### PR TITLE
Phase 1 submission

### PR DESCRIPTION
**Pull request by cbrxyz**

### CODE REVIEW

**Review by caguero — CHANGES_REQUESTED** [review]
Thanks for your VRX submission!

* [ ] Compliance tests for component and propulsion configurations passed.
* [x] Successfully able to access Docker image.
* [ ] Your video is reachable.
* [ ] Verified that the WAMV is active in the stationkeeping task.

Your WAM-V isn't generated properly. There's an issue in the `wamv_pinger` section. The field `name` should be renamed to `sensor_name`.

Although your video is reachable, it shows VRX in Gazebo Classic. The goal is to show a video of VRX running in the current environment (in Gazebo).

We don't see activity in your WAM-V. Additionally, the following error has been found when running your submission:

```
 * RLException: ERROR: unable to contact ROS master at [http://172.16.0.22:11311]
The traceback for the exception was written to the log file
```

As a reminder, the simulation exposes a ROS 2 API. Not sure if this is an internal error message or you're expecting a ROS 1 system (not the case).

Please, update and retest your submission following the [instructions from the phase 1 tutorial](https://github.com/osrf/vrx/wiki/vrx_2023-phase1_hello_world#submission-testing).

**Comment by caguero** [comment]
Any chance you can address the format issues and the video update in the next hour?

**Comment by caguero** [comment]
Unfortunately, we can't accept your submission as it is. If you submit a new video with the Gazebo-based VRX environment in the next days, you'll qualify for Phase 2.

**Comment by caguero** [comment]
@cbrxyz  , friendly ping.

**Comment by cbrxyz** [comment]
Hi Carlos, sorry, not sure why I didn't receive emails for this thread.

Sorry about the issues with our submission format. We misread the README and thought that Noetic was still going to be supported by the competition environment this year (we have just been using a previous commit of the VRX software) for testing, so we didn't see any issue with our setup. We're probably going to try to use the ROS 1 - ROS 2 bridge for VRX, because we won't have enough time to migrate to ROS 2 before phases 2/3.

We'll send the updates ASAP! Thanks for your help.

**Comment by j-herman** [comment]
In case you haven't seen the starter bridge that we tested out, here's the link:
https://github.com/j-herman/humble-noetic-bridge
Let us know how it goes!

**Comment by cbrxyz** [comment]
Thanks Jessica! We've started playing around with it and trying to make it work, and it's going good so far! We're starting to integrate it with our current stack, and we'll let you know how it goes! Thanks for setting that up!

**Pull request closed without merging**
