### PR TITLE
2023 rehearsal team osrf

### PR DESCRIPTION
**Pull request by Popfan999552**
For coolcats phase2

### CODE REVIEW

**Review by caguero — CHANGES_REQUESTED** [review]
Thanks for your VRX submission!

* [x] Compliance tests for component and propulsion configurations passed.
* [x] Successfully able to access Docker image.
* [ ] Verified that the WAMV is active in the stationkeeping task.

I don't see activity in your WAM-V during stationkeeping. While the simulation is running, I can't access to your `vrx-competitor-system` Docker container. 

I saw the following error while testing:

```
Traceback (most recent call last):
  File "//coolcats.py", line 17, in <module>
    import pymap3d
ModuleNotFoundError: No module named 'pymap3d'
```

Could you check on your side following the [Docker testing instructions](https://github.com/osrf/vrx/wiki/vrx_2023-testing)?

**Comment by caguero** [comment]
@Popfan999552 , friendly ping.

**Comment by Popfan999552** [comment]
Yes, we have submitted a pull request with a fixed dockerfile, thank you.

**Review by caguero — COMMENTED** [review]
I can access your docker container now and the WAM-V shows activity during stationkeeping. I see that the WAM-V approaches the target but keeps spinning without stopping at the right orientation.

**Review by caguero — APPROVED** [review]

**Pull request merged**
