### PR TITLE
Team Minion submission for 2023/Phase1_HelloWorld

### PR DESCRIPTION
**Pull request by gigiucles**
Submission is for changed WAMV and video displaying progress.  Docker is also attached, but we were having some issues with running it.

### CODE REVIEW

**Review by caguero — CHANGES_REQUESTED** [review]
Thanks for your VRX submission!

* [ ] Compliance tests for component and propulsion configurations passed.
* [x] Successfully able to access Docker image.
* [x] Your video is reachable.
* [ ] Verified that the WAMV is active in the stationkeeping task.

You're trying to remove the `video_link.txt` from the `example_team`. Could you restore that file in your branch please?

We can't generate your WAM-V. It looks like some indentation/spacing issue. I was able to manually generate it with the following files:

```
engine:
  - prefix: "left"
    position: "-2.373776 1.027135 0.318237"
    orientation: "0.0 0.0 0.0"
  - prefix: "right"
    position: "-2.373776 -1.027135 0.318237"
    orientation: "0.0 0.0 0.0"
```

```
wamv_camera:
    - name: front_left_camera
      visualize: False
      x: 0.75
      y: 0.1
      z: 1.5
      R: 0.0
      P: ${radians(15)}
      Y: 0.0
      post_Y: 0.0
    - name: front_right_camera
      visualize: False
      x: 0.75
      y: -0.1
      z: 1.5
      R: 0.0
      P: ${radians(15)}
      Y: 0.0
      post_Y: 0.0
    - name: far_left_camera
      visualize: False
      x: 0.75
      y: 0.3
      z: 1.5
      R: 0.0
      P: ${radians(15)}
      Y: 0.0
      post_Y: 0.0
wamv_gps:
    - name: gps_wamv
      x: -0.85
      y: 0.0
      z: 1.3
      R: 0.0
      P: 0.0
      Y: 0.0
wamv_imu:
    - name: imu_wamv
      x: 0.3
      y: -0.2
      z: 1.3
      R: 0.0
      P: 0.0
      Y: 0.0
lidar:
    - name: lidar_wamv
      type: 32_beam
      x: 0.7
      y: 0.0
      z: 1.8
      R: 0.0
      P: ${radians(8)}
      Y: 0.0
      post_Y: 0.0
    - name: aft_32
      type: 32_beam
      x: -0.8
      y: 0.0
      z: 1.8
      R: 0.0
      P: ${radians(8)}
      Y: ${radians(180)}
wamv_ball_shooter:
    - name: ball_shooter
      x: 0.55 
      y: -0.3 
      z: 1.3
      pitch: ${radians(-20)}
      yaw: 0.0
wamv_pinger:
    - sensor_name: receiver
      position: 1.0 0 -1.0

```

We don't see activity in your WAM-V. Additionally, the following error has been found when running your submission:

```
docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/ros_entrypoint.sh": permission denied: unknown.
ERRO[0000] error waiting for container: context canceled
```

Please, update and retest your submission following the [instructions from the phase 1 tutorial](https://github.com/osrf/vrx/wiki/vrx_2023-phase1_hello_world#submission-testing).

**Comment by caguero** [comment]
Any chance you can address the format issues in the next hour? Strictly speaking not necessary for qualifying but a good opportunity to make sure that you got the WAM-V generation and docker link correct. Otherwise, we'll test it in phase 2.

**Comment by gigiucles** [comment]
I restored the file and tried to fix the issue with the indentation on the WAMV, unfortunately we were still not able to solve our docker issue, it is still giving us the same error you received.

**Comment by caguero** [comment]
> I restored the file and tried to fix the issue with the indentation on the WAMV, unfortunately we were still not able to solve our docker issue, it is still giving us the same error you received.

Thanks! Could you also update your `dockerhub_image.txt` file? You need to remove the `docker pull` from it.

**Comment by gigiucles** [comment]
Other than the fact the docker file itself needs to be updated does it look good now?

**Review by caguero — APPROVED** [review]
Thanks for the updates. It looks much better. I can download your image and generate your WAM-V automatically. Approving!

As for testing your solution within the Docker environment, I recommend you to go through the submission [instructions from the phase 1 tutorial](https://github.com/osrf/vrx/wiki/vrx_2023-phase1_hello_world#submission-testing) to test your solution before phase 2. You can do that by yourself to make sure things are working before you make the next submission.

**Pull request merged**
