### PR TITLE
2023 phase1 ouxt polaris

### PR DESCRIPTION
**Pull request by kentaokamoto**
This submission is for phase 1. This is not created for any task.

### CODE REVIEW

**Review by caguero — CHANGES_REQUESTED** [review]
Thanks for your VRX submission!

* [ ] Compliance tests for component and propulsion configurations passed.
* [ ] Successfully able to access Docker image.
* [x] Your video is reachable.
* [ ] Verified that the WAMV is active in the stationkeeping task.

The content of the `dockerhub_image.txt` is not in the right format. I think in your case it should be:
```
wamvtan/vrx:latest
```

The `component_config.yaml` has an error. The `wamv_pinger` section should contain a field `sensor_name` and you're using `name`.

We don't see activity in your WAM-V. Additionally, the following error has been found when running your submission:

```
['xacro', '/home/config/wamv_target.urdf', 'namespace:=wamv', 'locked:=true', 'vrx_sensors_enabled:=true', 'thruster_config:=H']
Error [parser.cc:845] Error parsing XML from string: Error=XML_ERROR_EMPTY_DOCUMENT ErrorID=13 (0xd) Line number=0
[ERROR] [launch]: Caught exception in launch (see debug for traceback): Error Code 30: Msg: Unable to read SDF string:
```

Please, update and retest your submission following the [instructions from the phase 1 tutorial](https://github.com/osrf/vrx/wiki/vrx_2023-phase1_hello_world#submission-testing).

**Comment by caguero** [comment]
Any chance you can address the format issues in the next hour? Strictly speaking not necessary for qualifying but a good opportunity to make sure that you got the WAM-V generation and docker link correct. Otherwise, we'll test it in phase 2.

**Review by caguero — APPROVED** [review]
Thanks for the update. I can now access your DockerHub image and successfully generate your WAM-V. Approving!

As for testing your submission in Docker, I recommend you to go through the submission [instructions from the phase 1 tutorial](https://github.com/osrf/vrx/wiki/vrx_2023-phase1_hello_world#submission-testing) to test your solution (when ready) before phase 2. You can do that by yourself to make sure things are working before you make the next submission.

**Comment by kentaokamoto** [comment]
Thank you for your review. I fixed the component_config.yaml and Docker link. I need time to show the station keeping

**Pull request merged**
