### PR TITLE
Team NaviGator submission for VRX 2022 Phase 3

### PR DESCRIPTION
**Pull request by alexperez33**
This submission attempts all the tasks. Please let us know if there are any issues! Thanks for the awesome season!

### CODE REVIEW

**Comment by j-herman** [comment]
* [x] Compliance tests for component and propulsion configurations passed.
* [x] Successfully able to access Docker image.

Verified that the WAMV is active in the following tasks:
* [x] Stationkeeping
* [x] Wayfinding
* [x] Perception 
* [x] Wildlife
* [x] Gymkhana
* [x] Scan, Dock, Deliver 

It looks like everything is communicating correctly, so I will go ahead and merge this.  Thanks for the submission!  If you want to make any changes up through the deadline, you are still welcome to submit via a new PR.

**Comment by alexperez33** [comment]
@j-herman I noticed that the Perception check box is not checked. It should be active during this task as well. Was something wrong?

**Comment by M1chaelM** [comment]
@alexperez33 I see activity in perception also so I checked that box too. I'm just checking to see whether the score changes, but I also see your container is producing output, and there is nothing that stands out as obviously wrong.

**Comment by alexperez33** [comment]
Great! Thanks!

**Pull request merged**
