### PR TITLE
Team Minion submission for 2022/troubleshooting

### PR DESCRIPTION
**Pull request by ayarst**

### CODE REVIEW

**Comment by ayarst** [comment]
This submission is expected to work for station_keeping, wayfinding, and scan_dock_deliver.

**Comment by M1chaelM** [comment]
Testing now...
* [x] Compliance tests for component and propulsion configurations passed.
* [x] Successfully able to access Docker image.

Verified that the WAMV is active in the following tasks:
* [x] Stationkeeping
* [x] Wayfinding
* [ ] Perception 
* [ ] Wildlife
* [ ] Gymkhana
* [x] Scan, Dock, Deliver

**Comment by M1chaelM** [comment]
The good news is your container is now definitely running and I'm seeing output during the three tasks. However, the WAMV still doesn't move for any of them. Are you able to run a test yourself locally using your docker image and our server image? The instructions for doing this are here:  https://github.com/osrf/vrx/wiki/vrx_2022-testing

I think running a trial yourself will give you some useful output and speed up debugging.

**Comment by M1chaelM** [comment]
Looking into this a little further, I'm seeing these error messages, which might help:
```
ERROR: cannot launch node of type [robot_localization/ekf_localization_node]: robot_localization
ROS path [0]=/opt/ros/noetic/share/ros
ROS path [1]=/minion_ws/src
ROS path [2]=/opt/ros/noetic/share
ERROR: cannot launch node of type [robot_localization/navsat_transform_node]: robot_localization
ROS path [0]=/opt/ros/noetic/share/ros
ROS path [1]=/minion_ws/src
ROS path [2]=/opt/ros/noetic/share
ERROR: cannot launch node of type [robot_state_publisher/robot_state_publisher]: robot_state_publisher
ROS path [0]=/opt/ros/noetic/share/ros
ROS path [1]=/minion_ws/src
ROS path [2]=/opt/ros/noetic/share
ERROR: cannot launch node of type [joint_state_publisher/joint_state_publisher]: joint_state_publisher
ROS path [0]=/opt/ros/noetic/share/ros
ROS path [1]=/minion_ws/src
ROS path [2]=/opt/ros/noetic/share
ERROR: cannot launch node of type [rviz/rviz]: rviz
ROS path [0]=/opt/ros/noetic/share/ros
ROS path [1]=/minion_ws/src
ROS path [2]=/opt/ros/noetic/share
```

**Comment by ayarst** [comment]
@M1chaelM I updated the docker image and I believe it now has all the necessary dependencies. I tested it on my machine using the method outlined in the tutorial you sent. I ran trial 0 of the wayfinding task and the boat was moving. However, gazebo never opened so I was unable to determine if it was performing as expected. When I played back the gazebo log, I saw the boat moving, but I did not see the waypoint markers, so I was still unable to verify that it was working properly.

**Comment by ayarst** [comment]
I added gazebo11 and rviz to the dockerfile installs, so I will rebuild everything and test the task again.

**Comment by M1chaelM** [comment]
@ayarst That sounds promising. Unfortunately the waypoint markers don't appear in the playback, but if you need to see them you can achieve this by running the trial manually. The tutorial for doing this is here: https://github.com/osrf/vrx/wiki/tutorials-vrx_docker_manual_trial

You can also get performance information in various levels of detail by looking at your score, or opening a bash session into your container while it's running and listing topics of interest (see https://github.com/osrf/vrx/wiki/tutorials-vrx_docker_examine)

**Comment by M1chaelM** [comment]
I'm now seeing WAMV activity in all 3 tasks you expected. This is usually all we test for, since it means the competition mechanics are not broken. However, I'm also not seeing any glaring error messages, and the WAMV behavior seems reasonable. For further testing, you can use the tutorials linked above to run trials, get your scores, etc. Congratulations on getting this working!

If you have any extra questions feel free to post them. Otherwise I will merge this shortly.

**Comment by ayarst** [comment]
Thank you so much for all your help! We really appreciate it!

**Pull request merged**
