### PR TITLE
2022 phase2 byuvrx

### PR DESCRIPTION
**Pull request by Caden-Ellis77**
This will work for tasks 1, 2, 3. Not 4, 5, 6. I also created an erroneous pull request earlier and closed it, perhaps it should be deleted somehow? It has a lot of source code in it.

### CODE REVIEW

**Comment by M1chaelM** [comment]
* [x] Compliance tests for component and propulsion configurations passed.
* [x] Successfully able to access Docker image.

Verified that the WAMV is active in the following tasks:
* [x] Stationkeeping
* [x] Wayfinding
* [ ] Perception 
* [ ] Wildlife
* [ ] Gymkhana
* [ ] Scan, Dock, Deliver

**Comment by M1chaelM** [comment]
I am seeing the WAMV move forward in a straight line for all tasks. Is this expected?

**Comment by M1chaelM** [comment]
Overall, the current behavior is the same as what would be produced by running the example image created by the tutorial. If you made further changes, is it possible you may not have committed them before pushing your image to the repository?

**Comment by Caden-Ellis77** [comment]
Yes, we followed the tutorial verbatim and it looks like our "./run_my_system.sh" just does the forward command. We changed that to run our competition launch file, however our package can't be found. I believe it's because our source code is not in our docker image. So when we create the image, we should clone our source code in the home directory I am guessing? And we don't have to worry about any environment stuff, because you guys will have that in your docker. We just need our source code put into the docker, correct? This is our first time using docker, we just wanted to clarify

**Comment by M1chaelM** [comment]
Yes, your docker image will need to contain the code you want to run. I can help you troubleshoot. Are you using option 1 or option 2 of [the tutorial](https://github.com/osrf/vrx/wiki/tutorials-Creating%20a%20Dockerhub%20image%20for%20submission)?

**Comment by M1chaelM** [comment]
The following assumes you are using option 1 of the tutorial linked above. If you are using option 2 let me know and I'll send another response. I just wanted to make sure you got a timely answer to your questions:
* Yes, one way to get your code into the container would be to clone the source code into the home directory, build it (if it needs to be built), and then make the changes persistent using the `docker commit` command, as described in the tutorial.
* Your container still needs to source any relevant `setup.bash` files. If you followed the tutorial, the `ros_entrypoint.sh` file you created will source the `setup.bash` for the `noetic`. If the code you are adding involves your own ros workspace, you may need to also source the `setup.bash` for that workspace (as you would when developing on a local machine).

**Comment by Caden-Ellis77** [comment]
We were using option 1. I'll add the source code and push it up, the docker repo name will have to change though. (Our current one has an error that so that we can't run it)

**Comment by Caden-Ellis77** [comment]
I think I have sourced everything, but I am getting "roslaunch" command not found when I test. Do I need to do the ros install steps as well?

**Comment by Caden-Ellis77** [comment]
It looks like I may have to do the ROS install in the docker. Does this sound normal?
What happens if we can't get it to work by today?

**Comment by Caden-Ellis77** [comment]
Alright, should be working now

**Comment by M1chaelM** [comment]
Apologies for the delayed reply. Yes, if you need to call ros executables in your solution it is normal to install ros. I will test this again now. If it doesn't work you will still proceed to phase 3. We just won't be able to calculate your score for the tasks you've completed so far.

**Review by M1chaelM — APPROVED** [review]
Now seeing the expected behavior. Thanks for the submission! Glad you got this fixed.

**Pull request merged**
