### PR TITLE
Phase 2 2023 Team Illusion Submission

### PR DESCRIPTION
**Pull request by thrzl**

### CODE REVIEW

**Review by caguero — APPROVED** [review]
Thanks for your VRX submission!

* [x] Compliance tests for component and propulsion configurations passed.
* [x] Successfully able to access Docker image.
* [x] Verified that the WAMV is active in the stationkeeping task.

All looking good!

**Review by caguero — CHANGES_REQUESTED** [review]
Minor request:

Could you leave your phase1 files untouched? This pull request should only contribute to phase2 in your case.

**Comment by thrzl** [comment]
I'm a little confused; I don't see any changes to the phase1 files. I can still see all of them, and the last commit I see in that directory is commit 0561220 on my end. Am I looking at the wrong thing?

**Comment by caguero** [comment]
> I'm a little confused; I don't see any changes to the phase1 files. I can still see all of them, and the last commit I see in that directory is commit [0561220](https://github.com/osrf/vrx-events/commit/056122096692472ff59977221686cfbdf434fb4d) on my end. Am I looking at the wrong thing?

You can see on the `Files changed` tab in this pull request that you're committing seven files and it should be just three files. It's probably related with how you created your branch for this PR. If you haven't changed anything from phase 1 I think it should be fine when we merge it.

**Comment by thrzl** [comment]
That is actually very interesting; I can assure you we haven't changed anything from phase 1 though. No clue why it's counting the phase 1 files as changed, though.

**Comment by ChaudiereNoire** [comment]
It is undoubtedly my fault. I used the same machine that we originally used to create the Phase 1 image to test the team's docker image after it was uploaded for Phase 2. It acted really screwy, with the GPS on the docker image failing to provide data, so I quick-like built up a new test box to prove to myself that everything was going to be OK. I probably touched the wrong files in my haste. We have not actually changed the Phase 1 files, at least intentionally.

**Comment by ChaudiereNoire** [comment]
I do have one concern. Is there something we actually have to do to satisfy this request?

**Comment by caguero** [comment]
> I do have one concern. Is there something we actually have to do to satisfy this request?

You could have updated your patch to not include phase 1 files but it's OK, the merge won't fail.

**Review by caguero — APPROVED** [review]

**Pull request merged**
