### PR TITLE
2023 challenge team osrf

### PR DESCRIPTION
**Pull request by lw76**
Added capabilities for camera color identification

### CODE REVIEW

**Review by caguero — CHANGES_REQUESTED** [review]
Thanks for your submission!

Unfortunately, your submission is not committing new files under the `phase3_vrx_challenge/<YOUR_TEAM_NAME>` directory. Please, commit within the next 24 hours your three submission files within the appropriate directory as specified in 

https://github.com/osrf/vrx/wiki/vrx_2023-phase3_challenge#submission-format

**Comment by lw76** [comment]
Sorry about that! The files must have gone away with the phase 2 branch when I switched to this one. Do you see them now?

**Comment by caguero** [comment]
> Sorry about that! The files must have gone away with the phase 2 branch when I switched to this one. Do you see them now?

I do see the files now. There's one conflict you should fix. I tested this submission as it is.

Thanks for your submission!

* [x] Compliance tests for component and propulsion configurations passed.
* [x] Successfully able to access Docker image.
* [ ] Verified that the WAMV is active in the stationkeeping task

The WAM-V is moving forward looking like it's executing the demo code where forward commands are applied. It's not trying to do real stationkeeping. I recommend you to go through the validation tutorial.

https://github.com/osrf/vrx/wiki/vrx_2023-validation

Please, resubmit no later than 24h from my first comment.

**Comment by lw76** [comment]
Just made the modifications. Let me know if station keeping is working. We should have capability to navigate, station keep, and identify colors of the buoys in Task 3 but not identify objects.

**Comment by caguero** [comment]
> Just made the modifications. Let me know if station keeping is working. We should have capability to navigate, station keep, and identify colors of the buoys in Task 3 but not identify objects.

No luck, your WAM-V is still inactive. I accessed it your competitor instance and I realized that you have installed ROS Noetic (??). Not sure if it's on purpose but it should be Humble.

**Comment by lw76** [comment]
Dear Carlos,

  The docker system is from a machine that had the legacy version of VRX
installed last year, but all of the code is written to work with ROS
Humble. I will work to remedy this issue soon.

Lindsay

**Comment by caguero** [comment]
> Dear Carlos, The docker system is from a machine that had the legacy version of VRX installed last year, but all of the code is written to work with ROS Humble. I will work to remedy this issue soon. Lindsay

I can confirm that your image is now on ROS 2 Humble. However, it's missing the `ros-humble-ros-gzgarden` package. Without this package you won't be able to subscribe to the `/vrx/task/info` topic. See one of the latest post on `Discord`.

**Pull request merged**
