### PR TITLE
Team PENShip submission for VRX Phase 1

### PR DESCRIPTION
**Pull request by rlggyp**

### CODE REVIEW

**Review by caguero — CHANGES_REQUESTED** [review]
Thanks for your VRX submission!

* [ ] Compliance tests for component and propulsion configurations passed.
* [x] Successfully able to access Docker image.
* [x] Your video is reachable.
* [ ] Verified that the WAMV is active in the stationkeeping task.

There seems to be a problem in your `thruster_config.yaml`. It generates an error when trying to generate your WAM-V. I think it's an indentation issue. I managed to generate it successfully with the following content:

```
engine:
  - prefix: "left"
    position: "-2.373776 1.027135 0.318237"
    orientation: "0.0 0.0 0.0"
  - prefix: "right"
    position: "-2.373776 -1.027135 0.318237"
    orientation: "0.0 0.0 0.0"
  - prefix: "middle"
    position: "0 0 0.318237"
    orientation: "0.0 0.0 1.570796"
```

We don't see activity in your WAM-V. Is this expected?

Please, update and retest your submission following the [instructions from the phase 1 tutorial](https://github.com/osrf/vrx/wiki/vrx_2023-phase1_hello_world#submission-testing).

**Comment by rlggyp** [comment]
Thank you for reviewing. I tried generating the WAM-V without encountering any issues. Here is the photo

image

**Comment by rlggyp** [comment]
We can run the customized WAM-V model in the keep station task, as seen in the video available at our latest link.

commit 59a5feb

**Review by caguero — APPROVED** [review]
I can generate your WAM-V successfully now!

Approving but you should look into running your code under the `vrx-docker` testing environment as described in the  [instructions from the phase 1 tutorial](https://github.com/osrf/vrx/wiki/vrx_2023-phase1_hello_world#submission-testing). I still don't see your WAM-V moving in the stationkeeping task.

**Pull request merged**
