### PR TITLE
2023 rehearsal team_Singaboat

### PR DESCRIPTION
**Pull request by singaboat2023**
Our latest progress.

The submission tackles tasks:
- Scan Dock and Delivery
- Station Keeping
- Follow The Path

Remarks: errors encountered during generating wamv

### CODE REVIEW

**Review by caguero — CHANGES_REQUESTED** [review]
Thanks for your submission! Could you review the submission format?

https://github.com/osrf/vrx/wiki/vrx_2023-phase2_dress_rehearsal#submission-format

Your file name conventions do not match the expected names. Could you update them please?

**Comment by caguero** [comment]
@singaboat2023 , friendly ping.

**Comment by caguero** [comment]
@singaboat2023 , could you please update the file names?

**Comment by caguero** [comment]
Closing for inactivity. Reopen if necessary.

**Comment by stevennedwinn** [comment]
Hi, sorry for the late reply, yes it has been changed accordingly

**Pull request closed without merging**
