### PR TITLE
2022 rehearsal team PACE

### PR DESCRIPTION
**Pull request by lijianwen1997**

### CODE REVIEW

**Review by caguero — CHANGES_REQUESTED** [review]
* [x] Compliance tests for component and propulsion configurations passed.
* [x] Successfully able to access Docker image.

Verified that the WAMV is active in the following tasks:
* [x] Stationkeeping
* [x] Wayfinding
* [ ] Perception 
* [x] Wildlife
* [x] Gymkhana
* [x] Scan, Dock, Deliver

**Comment by caguero** [comment]
Thanks for the submission. I was able to test the stationkeeping task but I don't observe any activity, the WAM-V doesn't move. Is that expected?

**Comment by jalilChavez** [comment]
Could you please send us the execution log so that we can see if we are missing a dependency in the docker image?

**Comment by lijianwen1997** [comment]
Sorry we did not configure the entry-point correctly. We have fixed that issue and uploaded the docker image(The name is still the same). Could you please verify our solution for task 1 to 6? Thanks!

**Review by M1chaelM — APPROVED** [review]
I'm seeing activity in every task except perception, which seems to crash. Given that this is very good overall and certainly allows us to test the current status of performance, I recommend we merge but I will wait for @caguero to approve.

**Review by caguero — APPROVED** [review]

**Pull request merged**
