### PR TITLE
2023 Hello World Team_Amore

### PR DESCRIPTION
**Pull request by lssuamore**
The submission tackles the video with docker image only been able to attempt task #1. WAMV Configuration files are the default from VRX, we are using for now those ones. Thank you! Team AMORE

### CODE REVIEW

**Review by caguero — CHANGES_REQUESTED** [review]
Thanks for your VRX submission!

* [x] Compliance tests for component and propulsion configurations passed.
* [ ] Successfully able to access Docker image.
* [x] Your video is reachable.
* [ ] Verified that the WAMV is active in the stationkeeping task.

Your `dockerhub_image.txt` isn't in the right format. Could you remove the `docker pull` from it please?

Although you mentioned that it should work, we don't see activity in your WAM-V in the `stationkeeping` task.

**Comment by lssuamore** [comment]
Hello Carlos, I did remove the docker pull from docker_image.txt . I pushed the repo again, please check if now is the right format. Also, when you run the docker, do you know if there is code running? Do you know how I can test it the way you run the docker? Thank you! Xavi/Team Amore

**Review by caguero — APPROVED** [review]
Thanks for the update. I can download your Docker image automatically, approving!

As for testing the solution via Docker in the wame way I'm doing it I recommend you to go through the submission [instructions from the phase 1 tutorial](https://github.com/osrf/vrx/wiki/vrx_2023-phase1_hello_world#submission-testing) to test your solution before phase 2. You can do that by yourself to make sure things are working before you make the next submission.

**Comment by lssuamore** [comment]
Hello Carlos. I got the wamv moving at task 1, but it is not working as expected because the wamv sensors are not been published. Do you know why this is happening? When I echo /wamv/robot_description the terminal outputs the following: 
data: '<?xml version="1.0" ?>

  

  <!-- |    Th...'
---
Also, if I try to echo any of the sensors, the topics are not been published. Let me know if there is any way to fix this. Thank you, Xavi/Team Amore

**Pull request merged**
