### PR TITLE
Team AMORE submission for 2023/vrx_challenge event.

### PR DESCRIPTION
**Pull request by lssuamore**
Hello, this is Team Amore doing the final commit for the 2023 VRX Challenge. Team Amore is attempting Task 1, 2, 3, 4, 5 , 6, 7 and 8. Note that we still have issues trying to run our solution with the vrx-docker. We still face the issue that the gps topic does not publish, so our WAMV is running on circles. Would you be able to check that the WAMV is running reasonable in each of the tasks? It does when we test our solution in our computer. 

On another note, I would like to say that the lidar is detecting waves, and the black buoys, I would like to say, that in our physical WAMV we use the VLP-16, and the lidar does not detect water, and black buoys. Black buoys is because the black color absorbs the lidar beams. I do not know if you guys made it on purpose that the lidar needs to detect water, and black buoys for making more challenging the competition, or you were not aware of this situation with the lidar. I thought making this note it might help you to develope more realistic simulations for future competitions. 

Other than that, I hope everything is well, and the team enjoyed a lot working on this competition! Team AMORE will be back in two years!

Thank you, 

Xavi Vicent/Team AMORE

### CODE REVIEW

**Review by caguero — APPROVED** [review]
Thanks for your submission!

* [x] Compliance tests for component and propulsion configurations passed.
* [x] Successfully able to access Docker image.
* [x] Verified that the WAMV is active in the stationkeeping task

The next step is to evaluate the docker image in the VRX simulation with the tasks/trials over the next few days.

I tested your solution with a few stationkeeping worlds and works OK. I verified that I could echo the GPS inside your Docker container:

```
root@3ffbfacbfcdb:/# ros2 topic echo /wamv/sensors/gps/gps/fix
header:
  stamp:
    sec: 9
    nanosec: 152000000
  frame_id: wamv/wamv/gps_wamv_link/navsat
status:
  status: 0
  service: 0
latitude: -33.72276876888639
longitude: 150.67399110174387
altitude: 1.3240922251716256
position_covariance:
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
position_covariance_type: 0
---
```

Good luck!

**Comment by lssuamore** [comment]
Thank you Carlos! 

Would you be able to confirm that our solution also works for the other tasks? Is it something you can check for us, and we can try to correct it in case it does not work? Or by rule, you can only check station keeping? 

Thank you for your time and work! 

Best, 

Xavi Vicent/Team Amore

**Comment by caguero** [comment]
> Thank you Carlos!
> 
> Would you be able to confirm that our solution also works for the other tasks? Is it something you can check for us, and we can try to correct it in case it does not work? Or by rule, you can only check station keeping?
> 
> Thank you for your time and work!
> 
> Best,
> 
> Xavi Vicent/Team Amore

I can't manually check all the tasks, sorry. I manually ran `wildlife4` for a minute and looked reasonable. I don't think you have any issues reading GPS data.

Good luck!

**Comment by lssuamore** [comment]
Thank you so much for your help, Carlos! I really appreciate it!

Best Regards, 

Xavi/Team Amore

**Pull request merged**
