### PR TITLE
Team GTMRG submission for 2022/rehearal event.

### PR DESCRIPTION
**Pull request by mroglan**
This should attempt tasks 1, 2, 3, but is still under development.

### CODE REVIEW

**Comment by M1chaelM** [comment]
* [x] Compliance tests for component and propulsion configurations passed.
* [x] Successfully able to access Docker image.

Verified that the WAMV is active in the following tasks:
* [ ] Stationkeeping
* [ ] Wayfinding
* [ ] Perception 
* [ ] Wildlife
* [ ] Gymkhana
* [ ] Scan, Dock, Deliver

**Comment by M1chaelM** [comment]
For the stationkeeping tasks I am seeing a lot of output but no movement of the WAMV. Is this expected?

**Comment by mroglan** [comment]
No, it is not expected. I believe it is a failure with our ros bridge; we
have been struggling with it in Docker.

**Comment by M1chaelM** [comment]
OK, thanks for explaining. Right now it looks like this problem affects all 3 tasks that you attempted. We will still accept your submission and you will still move on to phase 3, but you still have some time if you want to try to troubleshoot so we can give you a score on the tasks you completed. Let me know if you want me to test again.

**Review by M1chaelM — APPROVED** [review]
If there is no further activity planned I will go ahead and merge this in a few hours.

**Pull request merged**
