### PR TITLE
AMV_IITM submission for 2022/phase3 vrx event

### PR DESCRIPTION
**Pull request by adityajadhav99**
We expect WAMV to show **activity in all the 6 tasks**.
**Note**: For tasks **wayfinding**, **wildlife**, **gymkhana**, the WAMV will show some action only after some task **running time** has elapsed

### CODE REVIEW

**Comment by caguero** [comment]
Thanks for the submission!

* [x] Compliance tests for component and propulsion configurations passed.
* [x] Successfully able to access Docker image.

Verified that the WAMV is active in the following tasks:
* [x] Stationkeeping
* [ ] Wayfinding
* [ ] Wildlife

Stationkeeping shows WAM-V activity. However I tested wayfinding and wildlife and didn't see any activity during 40 seconds of running time. I see a few errors like this one in case it helps:

```
[ERROR] [1649856382.371750, 79.550000]: bad callback: <function animals_sub_callback at 0x7f73ad12a310>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/vrx_ws/src/VRX_iitm/wildlife_soln/scripts/wildlife_task.py", line 135, in animals_sub_callback
    goal_pose_seq = update_seq(goal_pose_list, wamv_initial_pose)
  File "/vrx_ws/src/VRX_iitm/wildlife_soln/scripts/wildlife_task.py", line 59, in update_seq
    distances_list[j] = (remaining_nodes_list[j][0]-pose_seq[-1][0])**2 + (remaining_nodes_list[j][1]-pose_seq[-1][1])**2
IndexError: list index out of range
```

**Comment by adityajadhav99** [comment]
@caguero thanks for the reply
We are currently trying to correct the above-mentioned errors. We have tested our updated solution on the vrx-server docker platform. For the wayfinding task, the score comes down to an expected value and when the task stops the **score suddenly increases to 200**.

You can see this in the image ([link](https://drive.google.com/file/d/1Fn269QRYduYgFEiatAklzUITgIXSNbha/view?usp=sharing)).

Could you suggest why this might be happening?

We tried testing it on our local systems and there the scoring works as expected.

**Comment by caguero** [comment]
> @caguero thanks for the reply We are currently trying to correct the above-mentioned errors. We have tested our updated solution on the vrx-server docker platform. For the wayfinding task, the score comes down to an expected value and when the task stops the **score suddenly increases to 200**.
> 
> You can see this in the image ([link](https://drive.google.com/file/d/1Fn269QRYduYgFEiatAklzUITgIXSNbha/view?usp=sharing)).
> 
> Could you suggest why this might be happening?
> 
> We tried testing it on our local systems and there the scoring works as expected.

This is an issue that we recently fixed (https://github.com/osrf/vrx/pull/456). I recommend to rebuild your Docker server image and make sure that you don't use cache.

Let me know when should I recheck your submission.

**Comment by adityajadhav99** [comment]
> > @caguero thanks for the reply We are currently trying to correct the above-mentioned errors. We have tested our updated solution on the vrx-server docker platform. For the wayfinding task, the score comes down to an expected value and when the task stops the **score suddenly increases to 200**.
> > You can see this in the image ([link](https://drive.google.com/file/d/1Fn269QRYduYgFEiatAklzUITgIXSNbha/view?usp=sharing)).
> > Could you suggest why this might be happening?
> > We tried testing it on our local systems and there the scoring works as expected.
> 
> This is an issue that we recently fixed ([osrf/vrx#456](https://github.com/osrf/vrx/pull/456)). I recommend to rebuild your Docker server image and make sure that you don't use cache.
> 
> Let me know when should I recheck your submission.

We removed the old vrx-server images from our local system and then followed the steps in the [testing tutorial](https://github.com/osrf/vrx/wiki/vrx_2022-testing) to bulid the server image. Still the scoring error mentioned above exists. Should this work equivalent to --no-cache?  or can you share the commands to do that?

**Comment by M1chaelM** [comment]
@adityajadhav99 Sorry this is a bit of a hassle. Could you check that you are using the latest version of `vrx-docker`? Line 111 of the Dockerfile should read 
```
RUN git clone -b 1.6.2 https://github.com/osrf/vrx.git
```
If that is right, then yes, you should be able to clear the cache by removing all the `vrx-server` images. You could also modify line 67 of the `build_image.bash` script so it reads:
```
docker build --no-cache --force-rm ${DOCKER_ARGS} --tag $image_plus_tag --build-arg USER=$USER --build-arg GROUP=$USER $BUILD_BASE $DIR/vrx-server && \
```
(Unfortunately this is a relatively unusual situation so we don't have an option built into the script to add this flag.)

**Comment by M1chaelM** [comment]
By the way, in case it gives you peace of mind, I have verified that when I run your `wayfinding` task the score does not jump to 200 on timeout.

**Comment by adityajadhav99** [comment]
@M1chaelM 
Thanks for you reply!
We have rebuilt the server image and the scoring now seems to work fine as expected.

We have now resolved our errors related to the tasks mentioned by @caguero above. Can you please test our solution **for all** the tasks now and see whether the wamv is active in all of them and let us know.

Thank you !

**Comment by M1chaelM** [comment]
Testing again
* [x] Compliance tests for component and propulsion configurations passed.
* [x] Successfully able to access Docker image.

Verified that the WAMV is active in the following tasks:
* [x] Stationkeeping
* [x] Wayfinding
* [x] Perception 
* [x] Wildlife
* [x] Gymkhana
* [x] Scan, Dock, Deliver

**Comment by M1chaelM** [comment]
Now seeing activity in all 6 tasks. Congratulations, and thanks for this submission. I'm going to merge now. After tonight we'll run and score the competition and the results will be announced at the awards party on 4/22 (as well as on the website). Good luck!

**Comment by VallabhD** [comment]
> Now seeing activity in all 6 tasks. Congratulations, and thanks for this submission. I'm going to merge now. After tonight we'll run and score the competition and the results will be announced at the awards party on 4/22 (as well as on the website). Good luck!

Thank you!!

**Comment by adityajadhav99** [comment]
Hello @M1chaelM 
We would like to know whether the solution for task 5 (Gymkhana) is working on the Docker platform (are we receiving any points?). 

When we were testing it on the Docker server, we found out while debugging that some of the relevant topics (created by us) didn't seem to receive any messages and that's why the WAMV wasn't performing as expected.

This issue was not seen while testing it on our local system and we were able to successfully complete difficulty level 0 and level 1 of the task. We are getting score of around 80 in both. We have recorded videos of the same which can be seen [here](https://drive.google.com/file/d/18Fxuc3LRjLcS76PXMABZ2wJ9JI8_WFUC/view?usp=sharing) and [here](https://drive.google.com/file/d/1BWdFVJOqm51OtBpNIjQoFoWMCsy3Nl86/view?usp=sharing). 

Thank You !!

**Pull request merged**
