### PR TITLE
2022/phase2_dress_rehearsal/wazzu_worms

### PR DESCRIPTION
**Pull request by FrancisGoncalves**
This submission was supposed to tackle tasks 1, 2, and 3 but while testing it and scoring it there was some problem with the docker image and the boat did not move. So, I do not think the solution will work for any task. This is unfortunate since when running our python scripts in our local machine the solutions seemed to work fairly well. We will try to debug this and get it working for phase 3, where we will also tackle tasks 4, 5, and 6 hopefully.

### CODE REVIEW

**Comment by M1chaelM** [comment]
* [x] Compliance tests for component and propulsion configurations passed.
* [x] Successfully able to access Docker image.

Verified that the WAMV is active in the following tasks:
* [ ] Stationkeeping
* [ ] Wayfinding
* [ ] Perception 
* [ ] Wildlife
* [ ] Gymkhana
* [ ] Scan, Dock, Deliver 

The next step is to evaluate run the docker image in the VRX simulation with the tasks/trials over the next few days.

**Comment by M1chaelM** [comment]
Sorry to hear about this difficulty. The problem we are seeing is that your image exits immediately when run from the entrypoint. This suggests that something is either causing a crash or all your scripts are finishing very quickly. You still have some time to debug this if you'd like to try to get them working. If I have time to help troubleshoot I'll reply here.

**Comment by FrancisGoncalves** [comment]
Thank you Michael, we are all out of town now. However, I hope we can figure out this problem for Phase 3 because our solutions were working well in the local machine.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Review by M1chaelM — APPROVED** [review]
Understood. In that case this works as expected and I will accept the submission. Thank you!

**Pull request merged**
