### PR TITLE
Team Minion Phase 3 Submission for VRX 2022.

### PR DESCRIPTION
**Pull request by charlestmontagnoli**
Works for all six tasks, please let us know if there are any issues and we will work to fix them as quickly as possible.

### CODE REVIEW

**Review by caguero — CHANGES_REQUESTED** [review]
Please, verify the submission format instructions, as you're not submitting the correct files:

https://github.com/osrf/vrx/wiki/vrx_2022-phase3_challenge#submission-format

**Comment by charlestmontagnoli** [comment]
I just realized what I’d done, I’ll be submitting the correct files when I get out of class in 2 hours.

**Comment by charlestmontagnoli** [comment]
I have committed the correct files, sorry about that mix-up. As stated before, we expect to be scoring in all six tasks.
Thank you!

**Review by caguero — COMMENTED** [review]
Thanks for the submission!

* [x] Compliance tests for component and propulsion configurations passed.
* [x] Successfully able to access Docker image.

Verified that the WAMV is active in the following tasks:
* [x] Stationkeeping
* [x] Wayfinding
* [ ] Perception 
* [x] Wildlife
* [ ] Gymkhana
* [ ] Scan, Dock, Deliver 

The score in the perception task doesn't show much activity and also I didn't see the WAM-V moving on gymkhana and scan_dock_deliver.

The submission is valid but just checking in case there's a silly mistake in these tasks.

**Comment by charlestmontagnoli** [comment]
Gymkhana and scan_dock_deliver take a good amount of time to plan a path, so it may just be idle path planning (unless they did nothing the entire time). Perception should be scoring, perhaps we aren't building it right in our docker. I'll give it a look and see what I can figure out.

**Comment by caguero** [comment]
> Gymkhana and scan_dock_deliver take a good amount of time to plan a path, so it may just be idle path planning (unless they did nothing the entire time). Perception should be scoring, perhaps we aren't building it right in our docker. I'll give it a look and see what I can figure out.

I see. For reference, I tested it for 60 seconds in the `running` state.

**Comment by charlestmontagnoli** [comment]
I think we may have messed up a build dependency for perception, because in testing we score very well on that task. I'll see if I can get it to function properly. Gymkhana and scan_dock_deliver may have a similar issue. I'm looking into it now to try and fix it and resubmit,

**Comment by charlestmontagnoli** [comment]
Would you be willing to let gymkhana and scan_dock_deliver run for a longer time? We have a path planner that may take longer than expected to plan in some instances.

**Comment by j-herman** [comment]
I'll take a look at these and see if the full run time helps.  Will be a bit of a delay as we're about to lose power but I should be able to get through it within the next hour.

**Comment by charlestmontagnoli** [comment]
I've rebuilt a new docker image and pushed the .txt file with the name of the new docker commit. We think it should work, however we were unable to run `run_trial.bash`. It tells us invalid docker credentials even though we've verified our login. We expect this docker to score points on all 6 runs as before. Please let me know if there are any updates. Thanks!

**Comment by j-herman** [comment]
I will take a look and see if I can run the script.
With the previous version, I ran gymkhana for ~3 minutes with no perceptible motion from the wamv.

**Comment by charlestmontagnoli** [comment]
We believe the previous version won't move on wildlife either then. The newest commit we believe will.

**Comment by j-herman** [comment]
I'm able to run the script - no permission errors.  However, I'm now getting a compilation error which is breaking the previously working tasks.  It looks like you may be missing a file...?

```


-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- ~~  traversing 1 packages in topological order:
-- ~~  - path_planner
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- +++ processing catkin package: 'path_planner'
-- ==> add_subdirectory(vrx2022submission/path_planner)
-- Using these message generators: gencpp;geneus;genlisp;gennodejs;genpy
-- Found OpenMP_C: -fopenmp  
-- Found OpenMP_CXX: -fopenmp  
-- Found OpenMP: TRUE   
-- path_planner: 2 messages, 0 services
CMake Warning at /opt/ros/noetic/share/catkin/cmake/catkin_package.cmake:166 (message):
  catkin_package() DEPENDS on 'OpenMP' but neither 'OpenMP_INCLUDE_DIRS' nor
  'OpenMP_LIBRARIES' is defined.
Call Stack (most recent call first):
  /opt/ros/noetic/share/catkin/cmake/catkin_package.cmake:102 (_catkin_package)
  vrx2022submission/path_planner/CMakeLists.txt:114 (catkin_package)


-- Configuring done
-- Generating done
-- Build files have been written to: /minion_ws/build
[  0%] Built target sensor_msgs_generate_messages_nodejs
[  0%] Built target tf2_msgs_generate_messages_py
[  0%] Built target std_msgs_generate_messages_nodejs
[  0%] Built target nav_msgs_generate_messages_nodejs
[  0%] Built target std_msgs_generate_messages_py
[  0%] Built target nav_msgs_generate_messages_py
[  0%] Built target nav_msgs_generate_messages_lisp
[  0%] Built target tf2_msgs_generate_messages_cpp
[  0%] Built target tf2_msgs_generate_messages_nodejs
[  0%] Built target std_msgs_generate_messages_lisp
[  0%] Built target actionlib_generate_messages_lisp
[  0%] Built target actionlib_generate_messages_nodejs
[  0%] Built target actionlib_generate_messages_py
[  0%] Built target actionlib_generate_messages_cpp
[  0%] Built target rosgraph_msgs_generate_messages_lisp
[  0%] Built target tf_generate_messages_eus
[  0%] Built target tf_generate_messages_nodejs
[  0%] Built target tf_generate_messages_cpp
[  0%] Built target sensor_msgs_generate_messages_py
[  0%] Built target nav_msgs_generate_messages_eus
[  0%] Built target tf2_msgs_generate_messages_eus
[  0%] Built target actionlib_msgs_generate_messages_eus
[  0%] Built target usv_msgs_generate_messages_cpp
[  0%] Built target geometry_msgs_generate_messages_eus
[  0%] Built target actionlib_msgs_generate_messages_py
[  0%] Built target nav_msgs_generate_messages_cpp
[  0%] Built target minion_controls_generate_messages_py
[  0%] Built target roscpp_generate_messages_py
[  0%] Built target _path_planner_generate_messages_check_deps_path_type
[  0%] Built target _path_planner_generate_messages_check_deps_path_planner
[  0%] Built target minion_bugs_generate_messages_cpp
[  0%] Built target tf2_msgs_generate_messages_lisp
[  0%] Built target minion_controls_generate_messages_eus
[  0%] Built target geographic_msgs_generate_messages_cpp
[  0%] Built target rosgraph_msgs_generate_messages_nodejs
[  0%] Built target minion_controls_generate_messages_cpp
[  0%] Built target minion_bugs_generate_messages_lisp
[  0%] Built target uuid_msgs_generate_messages_cpp
[  0%] Built target roscpp_generate_messages_eus
[  0%] Built target uuid_msgs_generate_messages_lisp
[  0%] Built target actionlib_generate_messages_eus
[  0%] Built target roscpp_generate_messages_nodejs
[  0%] Built target uuid_msgs_generate_messages_eus
[  0%] Built target rosgraph_msgs_generate_messages_cpp
[  0%] Built target usv_msgs_generate_messages_nodejs
[  0%] Built target std_msgs_generate_messages_cpp
[  0%] Built target roscpp_generate_messages_lisp
[  0%] Built target minion_controls_generate_messages_nodejs
[  0%] Built target minion_bugs_generate_messages_eus
[  0%] Built target rosgraph_msgs_generate_messages_py
[  0%] Built target std_msgs_generate_messages_eus
[  0%] Built target roscpp_generate_messages_cpp
[  0%] Built target tf_generate_messages_lisp
[  0%] Built target geometry_msgs_generate_messages_py
[  0%] Built target geometry_msgs_generate_messages_cpp
[  0%] Built target minion_bugs_generate_messages_nodejs
[  0%] Built target geometry_msgs_generate_messages_lisp
[  0%] Built target actionlib_msgs_generate_messages_cpp
[  0%] Built target tf_generate_messages_py
[  0%] Built target geometry_msgs_generate_messages_nodejs
[  0%] Built target actionlib_msgs_generate_messages_lisp
[  0%] Built target actionlib_msgs_generate_messages_nodejs
[  0%] Built target geographic_msgs_generate_messages_py
[  0%] Built target sensor_msgs_generate_messages_lisp
[  0%] Built target usv_msgs_generate_messages_lisp
[  0%] Built target sensor_msgs_generate_messages_eus
[  0%] Built target usv_msgs_generate_messages_eus
[  0%] Built target geographic_msgs_generate_messages_eus
[  0%] Built target geographic_msgs_generate_messages_nodejs
[  0%] Built target rosgraph_msgs_generate_messages_eus
[  0%] Built target minion_controls_generate_messages_lisp
[  0%] Built target usv_msgs_generate_messages_py
[  0%] Built target sensor_msgs_generate_messages_cpp
[  0%] Built target geographic_msgs_generate_messages_lisp
[  0%] Built target uuid_msgs_generate_messages_nodejs
[  0%] Built target uuid_msgs_generate_messages_py
[  6%] Built target path_planner_generate_messages_cpp
[  6%] Built target minion_bugs_generate_messages_py
[ 17%] Built target path_planner_generate_messages_py
[ 24%] Built target path_planner_generate_messages_lisp
[ 41%] Built target path_planner_generate_messages_nodejs
[ 41%] Built target path_planner_generate_messages_eus
[ 41%] Built target path_planner_generate_messages
[ 51%] Built target path_planner
[ 55%] Building CXX object vrx2022submission/path_planner/CMakeFiles/dock_planner_node.dir/src/dock_planner_node.cpp.o
[ 82%] Built target wildlife_encounter_node
[ 82%] Built target gymkhana_node
[ 82%] Built target path_planner_node
[ 82%] Built target wayfinding_node
[ 89%] Built target path_planner_demo
[ 96%] Built target stationkeeping_node
/minion_ws/src/vrx2022submission/path_planner/src/dock_planner_node.cpp:9:10: fatal error: docking/ActualBays.h: No such file or directory
    9 | #include <docking/ActualBays.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [vrx2022submission/path_planner/CMakeFiles/dock_planner_node.dir/build.make:63: vrx2022submission/path_planner/CMakeFiles/dock_planner_node.dir/src/dock_planner_node.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:560: vrx2022submission/path_planner/CMakeFiles/dock_planner_node.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
Base path: /minion_ws
Source space: /minion_ws/src
Build space: /minion_ws/build
Devel space: /minion_ws/devel
Install space: /minion_ws/install
####
#### Running command: "cmake /minion_ws/src -DCATKIN_WHITELIST_PACKAGES=path_planner -DCATKIN_DEVEL_PREFIX=/minion_ws/devel -DCMAKE_INSTALL_PREFIX=/minion_ws/install -G Unix Makefiles" in "/minion_ws/build"
####
####
#### Running command: "make -j16 -l16" in "/minion_ws/build"
####
Invoking "make -j16 -l16" failed
```

**Comment by charlestmontagnoli** [comment]
We do not get this compilation error on our end when building our docker image. Is it the docker tagged v:4.2?

**Comment by charlestmontagnoli** [comment]
dockin/actual_bays.h is a header file in our ‘docking’ node, it should be built before ‘path_planner’ is built. I can check to ensure the docker is doing this properly, but when we built v4.2 this error was never seen on our end.

**Comment by j-herman** [comment]
It should have pulled 4.2 - I used your newest .txt file.   I will recheck just in case.
@M1chaelM, if you have a minute to check this one it would be good to have a second opinion in case I have a system issue.

**Comment by M1chaelM** [comment]
@j-herman OK sure, I'll double check now.

**Comment by j-herman** [comment]
> @j-herman OK sure, I'll double check now.

Thanks!  I did confirm I have the correct version of their image but haven't yet rebuilt vrx-server.  Same issue appears when I try to run both stationkeeping and wildlife.

**Comment by M1chaelM** [comment]
I'm getting the same compilation error:

```
/minion_ws/src/vrx2022submission/path_planner/src/dock_planner_node.cpp:9:10: fatal error: docking/ActualBays.h: No such file or directory
    9 | #include <docking/ActualBays.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

**Comment by j-herman** [comment]
Same result here with the updated vrx-server image - I still see the same compile errors.
Possibly some of the changes to sort out the build dependency may have caused something else to be built out of order?  I don't have much information to help troubleshoot, but if you'd like to make any changes (either to fix 4.2 or to revert back to 4.1 where some tasks were working) I will run the checks again.

**Comment by M1chaelM** [comment]
The entrypoint command has changed quite a bit between v4.1 and v.4.2. I'm not sure whether this is intended. v4.1 uses the standard `/ros_entrypoint.sh` command, but v4.2 is using a shell script that tries to compile the workspace on the fly. The whole command is:
```
"/bin/sh -c '. /opt/ros/noetic/setup.sh  && cd /minion_ws  && catkin_make -DCATKIN_WHITELIST_PACKAGES=\"minion\"  && catkin_make -DCATKIN_WHITELIST_PACKAGES=\"minion_bugs\"  && catkin_make -DCATKIN_WHITELIST_PACKAGES=\"point_cloud_module\"  && catkin_make -DCATKIN_WHITELIST_PACKAGES=\"minion_controls\"  && catkin_make -DCATKIN_WHITELIST_PACKAGES=\"path_planner\"  && catkin_make -DCATKIN_WHITELIST_PACKAGES=\"docking\"  && catkin_make -DCATKIN_WHITELIST_PACKAGES=\"minion_vision\"  && catkin_make -DCATKIN_WHITELIST_PACKAGES=\"\"'"
```
I think this is probably an accident because even if it were to compile correctly I don't see a call to run anything.

**Comment by charlestmontagnoli** [comment]
That's not intended, I'm fixing it now.

**Comment by charlestmontagnoli** [comment]
I've rebuilt our docker image with a fix for the `docking/actual_bays.h` problem. I'd changed where the message was built and that must've caused a problem.

I'm not sure how the `/ros_entrypoint.sh` ended up changing... the current file looks like this:
`#!/bin/bash
set -e

# setup ros environment
source "/opt/ros/$ROS_DISTRO/setup.bash"

/run_my_system.bash`
Which is how it's always looked.

Either way, now that the docker has been rebuilt again I'm submitting with v4.3, I'm really hoping this time I've made no further errors.
Thank you for all your help, I greatly appreciate it.

**Comment by j-herman** [comment]
Excellent news!  I'll give it another shot now.

**Comment by j-herman** [comment]
* [x] Compliance tests for component and propulsion configurations passed.
* [x] Successfully able to access Docker image.

Verified that the WAMV is active in the following tasks:
* [x] Stationkeeping
* [x] Wayfinding
* [ ] Perception 
* [x] Wildlife
* [x] Gymkhana
* [x] Scan, Dock, Deliver 

I see motion in all of the tasks where I'd expect it now.  Still not sure the perception task is reporting correctly, but it does appear that the container is communicating so it may be working.  If you're good with this, I'll go ahead and merge the PR now.

**Comment by charlestmontagnoli** [comment]
Our docker is missing `apt-get install ros-noetic-vision-opencv`, which is why you couldn’t see any scoring in perception, unfortunately I didn’t have the time to fix it before the midnight deadline yesterday.

**Pull request merged**
