### PR TITLE
2022/phase2/team_hyperion

### PR DESCRIPTION
**Pull request by HyperionUWI**
- Our team is entirely new to Docker and encountered difficulty with the docker image process. We tested our code locally and it works for tasks 1, 2 and 4, but we are unsure of its performance within the Docker image. 
- We do plan to finish development of tasks 3, 5 and 6 for the Phase 3 submission
- This submission specifically tackles tasks 1, 2 and 4 but it won't work for tasks 3, 5 or 6.

### CODE REVIEW

**Comment by M1chaelM** [comment]
* [x] Compliance tests for component and propulsion configurations passed.
* [x] Successfully able to access Docker image.

Verified that the WAMV is active in the following tasks:
* [x] Stationkeeping
* [x] Wayfinding
* [ ] Perception 
* [x] Wildlife
* [ ] Gymkhana
* [ ] Scan, Dock, Deliver

**Comment by M1chaelM** [comment]
I'm currently seeing no WAMV activity for tasks 1, 2 or 4. It looks like the default entrypoint is being executed, but I don't see where any code has been added to the image. If you think it should contain your solution, could you say where in the directory structure I could find it?

If you built your container using option 1 of the [Docker Image tutorial](https://github.com/osrf/vrx/wiki/tutorials-Creating%20a%20Dockerhub%20image%20for%20submission) it may be that you did not commit your changes to the image before pushing it to dockerhub.

**Comment by HyperionUWI** [comment]
I do suspect that the changes were not committed. The specific directory that contains our solutions is supposed to be `/root/vrx_ws`. However, we cannot seem to figure out how to source that directory in the `ros_entrypoint.sh` as it says that it does not exist.

**Comment by M1chaelM** [comment]
Looking at your image, it seems that all the source scripts in `/root/vrx_ws/devel` are broken links to a directory called `/home/kevin/vrx_ws/devel` so this may be why you are seeing that error.

**Comment by HyperionUWI** [comment]
Ahh I understand, does this mean when I build my docker container that I have to copy over my vrx_ws into the container and do a catkin_make to generate the devel folder. This way the links won't be broken and I will be able to source it properly?

**Comment by M1chaelM** [comment]
Yes, I think that's one way to do it. If you are using option 1 of the tutorial you can either use `docker cp` to add files from a local machine, or if your code is in a repository you could just clone it into the image. Then you should be able to build it, and then use `docker commit` to make these changes persistent. Hopefully after that your source command will work as expected.

**Comment by HyperionUWI** [comment]
I will try these options, thank you for the help!

**Comment by HyperionUWI** [comment]
So, we were able to get our vrx_ws into the docker container by using the `COPY` command in the `Dockerfile`. However, when we try to build it using the `catkin_make`, we got the following error:
```
CMake Error at /opt/ros/noetic/share/catkin/cmake/catkinConfig.cmake:83 (find_package):
  Could not find a package configuration file provided by "xacro" with any of
  the following names:

    xacroConfig.cmake
    xacro-config.cmake

  Add the installation prefix of "xacro" to CMAKE_PREFIX_PATH or set
  "xacro_DIR" to a directory containing one of the above files.  If "xacro"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  vrx/wamv_description/CMakeLists.txt:3 (find_package)
```
I am sure there is an easy fix to this but given our minimal experience with Docker and ROS we are unsure how to move forward. Any suggestions would be appreciated.

**Comment by HyperionUWI** [comment]
> So, we were able to get our vrx_ws into the docker container by using the `COPY` command in the `Dockerfile`. However, when we try to build it using the `catkin_make`, we got the following error:
> 
> ```
> CMake Error at /opt/ros/noetic/share/catkin/cmake/catkinConfig.cmake:83 (find_package):
>   Could not find a package configuration file provided by "xacro" with any of
>   the following names:
> 
>     xacroConfig.cmake
>     xacro-config.cmake
> 
>   Add the installation prefix of "xacro" to CMAKE_PREFIX_PATH or set
>   "xacro_DIR" to a directory containing one of the above files.  If "xacro"
>   provides a separate development package or SDK, be sure it has been
>   installed.
> Call Stack (most recent call first):
>   vrx/wamv_description/CMakeLists.txt:3 (find_package)
> ```
> 
> I am sure there is an easy fix to this but given our minimal experience with Docker and ROS we are unsure how to move forward. Any suggestions would be appreciated.

So, we were able to debug this issue and we were able to build and run it. However, when testing using this [tutorial](https://github.com/osrf/vrx/wiki/vrx_2022-testing) we encounter the error below. Do you have any suggestions?
```
started roslaunch server http://172.16.0.20:44107/

SUMMARY
========

PARAMETERS
 * /rosdistro: noetic
 * /rosversion: 1.15.13

NODES
  /
    nav (navigation/nav)
    tasks (tasks/tasks)

RLException: ERROR: unable to contact ROS master at [http://172.16.0.22:11311]
The traceback for the exception was written to the log file
vrx entrypoint executed
```

**Comment by HyperionUWI** [comment]
@M1chaelM We were able to debug and properly trial our wamv for tasks 1, 2 and 4, where it works as expected. 

Can you test again and verify that you see activity for these tasks?

**Comment by M1chaelM** [comment]
Yes, I can test again now. I'm sorry to see no one responded to you earlier, but I'm glad you were able to debug.

**Review by M1chaelM — APPROVED** [review]
Great! I'm glad you were able to get this working. Everything now appears to be running as expected and we are seeing activity on tasks 1, and 4. Thank you for the submission!

**Comment by sentientghost** [comment]
Okay thats great thank you!

**Pull request merged**
