### PR TITLE
Team AMORE submission for 2022/rehearsal event.

### PR DESCRIPTION
**Pull request by lssuamore**
Hello; our team had significant difficulty with the Docker image process. We believe our image has code for Tasks 1-3. Please let us know if there are any difficulties.

Take care,

Team AMORE: LSSU, UniBz

### CODE REVIEW

**Comment by M1chaelM** [comment]
* [x] Compliance tests for component and propulsion configurations passed.
* [x] Successfully able to access Docker image.

Verified that the WAMV is active in the following tasks:
* [ ] Stationkeeping
* [ ] Wayfinding
* [ ] Perception 
* [ ] Wildlife
* [ ] Gymkhana
* [ ] Scan, Dock, Deliver

**Comment by M1chaelM** [comment]
In a preliminary check of the stationkeeping task, I'm seeing the error:
```
RLException: [VRX_AMORE.launch] is neither a launch file in package [amore] nor is [amore] a launch file name
The traceback for the exception was written to the log file
```
Is it possible your startup code does not source setup.bash?

**Comment by lssuamore** [comment]
I do believe we forgot to source setup.bash. Is there a way that we can go
in and edit the setup.bash on the current docker image?

**Comment by M1chaelM** [comment]
Sorry for the delay in responding. Yes, you can make this change to your docker image and push a new version. Please let me know when to test again. Thanks!

**Comment by lssuamore** [comment]
Hi Michael,

We resubmitted our Docker image, using the same git branch as the first submission. Are we correct in saying that the pull request from the first submission is automatically used for the second submission? We think this because we kept everything the same (except the tag is now v3), but we cannot create a new pull request. We think we are all set though, Let us know.

Take care,

Team AMORE

**Comment by M1chaelM** [comment]
Hi. There's no need to make a new PR. I will use this one. Testing again now.

**Comment by M1chaelM** [comment]
OK, unfortunately, it looks like somehow the entrypoint on this image was changed from the default `ros_entrypoint.sh` to `bash`. This causes the image to exit immediately. When I attempt to change the entrypoint back to `ros_entrypoint.sh` the original error returns. I will try to look into this more later if there is time, in case it is a quick fix.

**Review by M1chaelM — CHANGES_REQUESTED** [review]
Currently your logic is not running, but I think this can be corrected with relatively minor changes. First, in your `run_my_system.bash` file, please change the line that says:
```
source "~/catkin_ws/devel/setup.bash"
```
to
```
source "/root/catkin_ws/devel/setup.bash"
```
This should allow you to launch `VRX_AMORE.launch` in the next line. Second, your entrypoint has changed to `bash` for some reason, and needs to be changed back to `ros_entrypoint.sh`. To do this, you can run:
```
docker ps -a
```
to get your container ID, and then 
```
docker commit --change='ENTRYPOINT ["/ros_entrypoint.sh"]' <CONTAINER_ID>
```
to fix the entrypoint. This will create a new image with repository <none> and tag <none>. You can see it by running:
```
docker image ls
```
and looking for the most recent entry. The use the `docker tag` command to give it a tag so you can push it to your repository.

Unfortunately, even after those changes I still do not see movement of the WAMV, but it is at least running your code.

**Comment by lssuamore** [comment]
Hello Michael,

Do we still move on to phase 3?

Thanks,

Brad

**Review by M1chaelM — APPROVED** [review]

**Comment by M1chaelM** [comment]
Yes, definitely. I was hoping you might be able to make those last few changes, but instead I will merge this now and we will be in touch about additional docker support before the final phase of the competition. Thank you for your submission!

**Comment by lssuamore** [comment]
Current Docker container*

**Pull request merged**
