### PR TITLE
2022/rehearsal/team_AMV_IITM 

### PR DESCRIPTION
**Pull request by adityajadhav99**
This submission tackles tasks **1**, **2**, and **3** but it won't work for tasks **4**,  **5**, and **6**.

### CODE REVIEW

**Comment by M1chaelM** [comment]
* [x] Compliance tests for component and propulsion configurations passed.
* [x] Successfully able to access Docker image.

Verified that the WAMV is active in the following tasks:
* [x] Stationkeeping
* [x] Wayfinding
* [x] Perception 
* [ ] Wildlife
* [ ] Gymkhana
* [ ] Scan, Dock, Deliver

**Comment by adityajadhav99** [comment]
@M1chaelM 
In our solution of Task 2 (**Wayfinding**), the WAMV is not programmed to immediately start moving. It will be active after 5 seconds of the start of the "running time" of the Task.
Please do verify the same.
Thank you!

**Comment by M1chaelM** [comment]
@adityajadhav99 Thanks for this note. I am currently not seeing any movement on task 2 but I will try a longer run.

**Review by M1chaelM — APPROVED** [review]
Working as expected. Thanks for your submission! The next step is to evaluate run the docker image in the VRX simulation with the tasks/trials over the next few days.

**Pull request merged**
