### PR TITLE
Phase 3 Submission, PENShip 

### PR DESCRIPTION
**Pull request by rlggyp**

### CODE REVIEW

**Comment by rlggyp** [comment]
Hi @caguero, may i ask

We have been able to complete several tasks. How do you test our submission? Do you use `./run_trial.bash $TEAM $TASK $TRIAL`? refer to this [wiki](https://github.com/osrf/vrx/wiki/vrx_2023-testing#step-3-run-and-score-your-solution)

When I read the shell script `run_trial.bash`, I noticed that you are not passing the arguments `${TEAM}`, `${TASK}`, and `${TRIAL}`. How are competitor containers instructed to perform the task based on the provided arguments? Thank you.

**Review by caguero — CHANGES_REQUESTED** [review]
Thanks for your submission!

* [x] Compliance tests for component and propulsion configurations passed.
* [x] Successfully able to access Docker image.
* [ ] Verified that the WAMV is active in the stationkeeping task

While testing the `stationkeeping0` task, I cannot access inside your Docker container. I highly recommend to go through the testing instructions for debugging your solution. We'll retest your solution one more time after 24 hours.

**Comment by caguero** [comment]
> Thanks for your submission!
> 
> * [x]  Compliance tests for component and propulsion configurations passed.
> * [x]  Successfully able to access Docker image.
> * [ ]  Verified that the WAMV is active in the stationkeeping task
> 
> While testing the `stationkeeping0` task, I cannot access inside your Docker container. I highly recommend to go through the testing instructions for debugging your solution. We'll retest your solution one more time after 24 hours.

Indeed, for testing your submission, I'm running the `run_trial.bash` script. The arguments are read in lines 29-31.

**Comment by caguero** [comment]
> Hi @caguero, may i ask
> 
> We have been able to complete several tasks. How do you test our submission? Do you use `./run_trial.bash $TEAM $TASK $TRIAL`? refer to this [wiki](https://github.com/osrf/vrx/wiki/vrx_2023-testing#step-3-run-and-score-your-solution)
> 
> When I read the shell script `run_trial.bash`, I noticed that you are not passing the arguments `${TEAM}`, `${TASK}`, and `${TRIAL}`. How are competitor containers instructed to perform the task based on the provided arguments? Thank you.

Indeed, for testing your submission, I'm running the `run_trial.bash` script. The arguments are read in lines 29-31.

**Comment by rlggyp** [comment]
> Thanks for your submission!
> 
>     * [x]  Compliance tests for component and propulsion configurations passed.
> 
>     * [x]  Successfully able to access Docker image.
> 
>     * [ ]  Verified that the WAMV is active in the stationkeeping task
> 
> 
> While testing the `stationkeeping0` task, I cannot access inside your Docker container. I highly recommend to go through the testing instructions for debugging your solution. We'll retest your solution one more time after 24 hours.

Okay thanks for reviewing, we just added a script to ros_entrypoint.sh to run script automatically when creating container. [wiki](https://github.com/osrf/vrx/wiki/tutorials-vrx_docker_interactive#step-4-create-run_my_systembash)

**Comment by rlggyp** [comment]
> > Hi @caguero, may i ask
> > We have been able to complete several tasks. How do you test our submission? Do you use `./run_trial.bash $TEAM $TASK $TRIAL`? refer to this [wiki](https://github.com/osrf/vrx/wiki/vrx_2023-testing#step-3-run-and-score-your-solution)
> > When I read the shell script `run_trial.bash`, I noticed that you are not passing the arguments `${TEAM}`, `${TASK}`, and `${TRIAL}`. How are competitor containers instructed to perform the task based on the provided arguments? Thank you.
> 
> Indeed, for testing your submission, I'm running the `run_trial.bash` script. The arguments are read in lines 29-31.

previously I thought that the argument will be forwarded to the competitor container, that way we can run the task according to the argument that is forwarded. thanks for answering

**Comment by caguero** [comment]
> > > Hi @caguero, may i ask
> > > We have been able to complete several tasks. How do you test our submission? Do you use `./run_trial.bash $TEAM $TASK $TRIAL`? refer to this [wiki](https://github.com/osrf/vrx/wiki/vrx_2023-testing#step-3-run-and-score-your-solution)
> > > When I read the shell script `run_trial.bash`, I noticed that you are not passing the arguments `${TEAM}`, `${TASK}`, and `${TRIAL}`. How are competitor containers instructed to perform the task based on the provided arguments? Thank you.
> > 
> > 
> > Indeed, for testing your submission, I'm running the `run_trial.bash` script. The arguments are read in lines 29-31.
> 
> previously I thought that the argument will be forwarded to the competitor container, that way we can run the task according to the argument that is forwarded. thanks for answering

Still no luck, I can't access your Docker competitor's instance while running with:

```
docker exec -it vrx-competitor-system bash
```

**Comment by rlggyp** [comment]
> > > > Hi @caguero, may i ask
> > > > We have been able to complete several tasks. How do you test our submission? Do you use `./run_trial.bash $TEAM $TASK $TRIAL`? refer to this [wiki](https://github.com/osrf/vrx/wiki/vrx_2023-testing#step-3-run-and-score-your-solution)
> > > > When I read the shell script `run_trial.bash`, I noticed that you are not passing the arguments `${TEAM}`, `${TASK}`, and `${TRIAL}`. How are competitor containers instructed to perform the task based on the provided arguments? Thank you.
> > > 
> > > 
> > > Indeed, for testing your submission, I'm running the `run_trial.bash` script. The arguments are read in lines 29-31.
> > 
> > 
> > previously I thought that the argument will be forwarded to the competitor container, that way we can run the task according to the argument that is forwarded. thanks for answering
> 
> Still no luck, I can't access your Docker competitor's instance while running with:
> 
> ```
> docker exec -it vrx-competitor-system bash
> ```

thank you for reviewing, this is proof that I can access my own docker competitor, [video](https://youtu.be/Fwlt-pPqc1w)

**Comment by rlggyp** [comment]
here I'm trying to simulate when you use the `run_trial.bash` script, I can still log into my docker competitor, [video](https://youtu.be/XhZH79pS0Hg)

**Pull request merged**
