### PR TITLE
Team SINGABOAT-VRX Submission

### PR DESCRIPTION
**Pull request by Tinker-Twins**
Virtual RobotX (VRX) Competition 2022 submission from NTU's team SINGABOAT-VRX.

### CODE REVIEW

**Review by caguero — APPROVED** [review]
Thanks for your submission!

* [x] Compliance tests for component and propulsion configurations passed.
* [x] Successfully able to access Docker image.

Verified that the WAMV is active in the following tasks:
* [x] Stationkeeping
* [x] Wayfinding

I tested your submission with station keeping and wayfinding and I see WAM-V activity. Approving!

**Comment by Tinker-Twins** [comment]
We have attempted all 6 tasks of VRX Competition 2022 and consequenty expect WAM-V activity in all the 6 tasks. Could you kindly confirm this @caguero?

**Comment by caguero** [comment]
Sorry I meant that I only verified activity in station keeping and wayfinding. I tried wildlife and scan_dock_deliver and they seem to show WAM-V activity as well.

**Comment by Tinker-Twins** [comment]
Absolutely no problem @caguero! Although, could you please confirm activity in all the 6 tasks since we had a few dependency conflicts while building the container. A review of all 6 tasks with those nice check-boxes as in https://github.com/osrf/vrx-events/pull/90#pullrequestreview-941177352 will make our day! :wink:

**Comment by caguero** [comment]
Life is so short for not making your day if I can:

Verified that the WAMV is active in the following tasks:
* [x] Stationkeeping
* [x] Wayfinding
* [x] Perception 
* [x] Wildlife
* [x] Gymkhana
* [x] Scan, Dock, Deliver 

Gymkhana: I do see the WAM-V actuating the propellers and rotating a bit in place but it doesn't go chase the navigation channel. Not sure if related but I see two instances of this error message on the terminal:

```
[ERROR] [1649865410.591967, 9.940000]: bad callback: <bound method BuoyDetector.camera_callback of <singaboat_vrx.perception_module.BuoyDetector object at 0x7f85f41a4dc0>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/VRX_Workspace/src/SINGABOAT-VRX/singaboat_vrx/src/singaboat_vrx/perception_module.py", line 264, in camera_callback
    if area > min_area and aspect_ratio < 1: # Marker buoy has lower aspect ratio
UnboundLocalError: local variable 'min_area' referenced before assignment
```

**Comment by Tinker-Twins** [comment]
@caguero, we have updated the docker container image to resolve the error, kindly pull it again. On a side note, our solution to the gymkhana task is implemented in such a way that the WAM-V scans the environment for first 30 seconds, after which it starts moving towards the channel entrance. Kindly confirm WAM-V activity after 30-40 seconds (simulation time) have elapsed.

Again, a review of all 6 tasks with those nice check-boxes as in https://github.com/osrf/vrx-events/pull/90#issuecomment-1098230486 will make our day! :wink:

**Comment by caguero** [comment]
I don't see the WAM-V moving in the Gymkhana task. I do see activity in the WAM-V, which makes me think it's a problem in your code, more than a submission issue. Here are some errors that showed up in the terminal:

```
(singaboat_scene_perception.py:117): Gdk-CRITICAL **: 17:42:38.915: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
[ERROR] [1649871760.460030, 10.202000]: bad callback: <bound method BuoyDetector.lidar_callback of <singaboat_vrx.perception_module.BuoyDetector object at 0x7f3f8d260c70>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/VRX_Workspace/src/SINGABOAT-VRX/singaboat_vrx/src/singaboat_vrx/perception_module.py", line 435, in lidar_callback
    pc_clusters = numpy.array(open3d_point_cloud.cluster_dbscan(eps=0.3, min_points=dbscan_min_points, print_progress=False))
UnboundLocalError: local variable 'dbscan_min_points' referenced before assignment

[ERROR] [1649871760.466890, 10.210000]: bad callback: <bound method BuoyDetector.camera_callback of <singaboat_vrx.perception_module.BuoyDetector object at 0x7f3f8d260c70>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/VRX_Workspace/src/SINGABOAT-VRX/singaboat_vrx/src/singaboat_vrx/perception_module.py", line 266, in camera_callback
    if area > min_area and aspect_ratio < 1: # Marker buoy has lower aspect ratio
UnboundLocalError: local variable 'min_area' referenced before assignment

[ERROR] [1649871760.629808, 10.372000]: bad callback: <bound method BuoyDetector.lidar_callback of <singaboat_vrx.perception_module.BuoyDetector object at 0x7f3f8d260c70>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/VRX_Workspace/src/SINGABOAT-VRX/singaboat_vrx/src/singaboat_vrx/perception_module.py", line 435, in lidar_callback
    pc_clusters = numpy.array(open3d_point_cloud.cluster_dbscan(eps=0.3, min_points=dbscan_min_points, print_progress=False))
UnboundLocalError: local variable 'dbscan_min_points' referenced before assignment

[ERROR] [1649871760.632573, 10.375000]: bad callback: <bound method BuoyDetector.camera_callback of <singaboat_vrx.perception_module.BuoyDetector object at 0x7f3f8d260c70>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/VRX_Workspace/src/SINGABOAT-VRX/singaboat_vrx/src/singaboat_vrx/perception_module.py", line 266, in camera_callback
    if area > min_area and aspect_ratio < 1: # Marker buoy has lower aspect ratio
UnboundLocalError: local variable 'min_area' referenced before assignment

[ERROR] [1649871760.673958, 10.412000]: bad callback: <bound method BuoyDetector.lidar_callback of <singaboat_vrx.perception_module.BuoyDetector object at 0x7f3f8d260c70>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/VRX_Workspace/src/SINGABOAT-VRX/singaboat_vrx/src/singaboat_vrx/perception_module.py", line 435, in lidar_callback
    pc_clusters = numpy.array(open3d_point_cloud.cluster_dbscan(eps=0.3, min_points=dbscan_min_points, print_progress=False))
UnboundLocalError: local variable 'dbscan_min_points' referenced before assignment

[ERROR] [1649871760.680562, 10.423000]: bad callback: <bound method BuoyDetector.camera_callback of <singaboat_vrx.perception_module.BuoyDetector object at 0x7f3f8d260c70>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/VRX_Workspace/src/SINGABOAT-VRX/singaboat_vrx/src/singaboat_vrx/perception_module.py", line 266, in camera_callback
    if area > min_area and aspect_ratio < 1: # Marker buoy has lower aspect ratio
UnboundLocalError: local variable 'min_area' referenced before assignment

[ERROR] [1649871760.726677, 10.468000]: bad callback: <bound method BuoyDetector.lidar_callback of <singaboat_vrx.perception_module.BuoyDetector object at 0x7f3f8d260c70>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/VRX_Workspace/src/SINGABOAT-VRX/singaboat_vrx/src/singaboat_vrx/perception_module.py", line 435, in lidar_callback
    pc_clusters = numpy.array(open3d_point_cloud.cluster_dbscan(eps=0.3, min_points=dbscan_min_points, print_progress=False))
UnboundLocalError: local variable 'dbscan_min_points' referenced before assignment

[ERROR] [1649871760.731606, 10.474000]: bad callback: <bound method BuoyDetector.camera_callback of <singaboat_vrx.perception_module.BuoyDetector object at 0x7f3f8d260c70>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/VRX_Workspace/src/SINGABOAT-VRX/singaboat_vrx/src/singaboat_vrx/perception_module.py", line 266, in camera_callback
    if area > min_area and aspect_ratio < 1: # Marker buoy has lower aspect ratio
UnboundLocalError: local variable 'min_area' referenced before assignment

[ERROR] [1649871760.754634, 10.497000]: bad callback: <bound method BuoyDetector.camera_callback of <singaboat_vrx.perception_module.BuoyDetector object at 0x7f3f8d260c70>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/VRX_Workspace/src/SINGABOAT-VRX/singaboat_vrx/src/singaboat_vrx/perception_module.py", line 266, in camera_callback
    if area > min_area and aspect_ratio < 1: # Marker buoy has lower aspect ratio
UnboundLocalError: local variable 'min_area' referenced before assignment

[ERROR] [1649871760.803485, 10.545000]: bad callback: <bound method BuoyDetector.lidar_callback of <singaboat_vrx.perception_module.BuoyDetector object at 0x7f3f8d260c70>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/VRX_Workspace/src/SINGABOAT-VRX/singaboat_vrx/src/singaboat_vrx/perception_module.py", line 435, in lidar_callback
    pc_clusters = numpy.array(open3d_point_cloud.cluster_dbscan(eps=0.3, min_points=dbscan_min_points, print_progress=False))
UnboundLocalError: local variable 'dbscan_min_points' referenced before assignment

[ERROR] [1649871760.807420, 10.549000]: bad callback: <bound method BuoyDetector.camera_callback of <singaboat_vrx.perception_module.BuoyDetector object at 0x7f3f8d260c70>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/VRX_Workspace/src/SINGABOAT-VRX/singaboat_vrx/src/singaboat_vrx/perception_module.py", line 266, in camera_callback
    if area > min_area and aspect_ratio < 1: # Marker buoy has lower aspect ratio
UnboundLocalError: local variable 'min_area' referenced before assignment

[ERROR] [1649871760.833312, 10.575000]: bad callback: <bound method BuoyDetector.camera_callback of <singaboat_vrx.perception_module.BuoyDetector object at 0x7f3f8d260c70>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/VRX_Workspace/src/SINGABOAT-VRX/singaboat_vrx/src/singaboat_vrx/perception_module.py", line 266, in camera_callback
    if area > min_area and aspect_ratio < 1: # Marker buoy has lower aspect ratio
UnboundLocalError: local variable 'min_area' referenced before assignment

[ERROR] [1649871760.852938, 10.586000]: bad callback: <bound method BuoyDetector.lidar_callback of <singaboat_vrx.perception_module.BuoyDetector object at 0x7f3f8d260c70>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/VRX_Workspace/src/SINGABOAT-VRX/singaboat_vrx/src/singaboat_vrx/perception_module.py", line 435, in lidar_callback
    pc_clusters = numpy.array(open3d_point_cloud.cluster_dbscan(eps=0.3, min_points=dbscan_min_points, print_progress=False))
UnboundLocalError: local variable 'dbscan_min_points' referenced before assignment

[ERROR] [1649871760.853580, 10.595000]: bad callback: <bound method BuoyDetector.camera_callback of <singaboat_vrx.perception_module.BuoyDetector object at 0x7f3f8d260c70>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/VRX_Workspace/src/SINGABOAT-VRX/singaboat_vrx/src/singaboat_vrx/perception_module.py", line 266, in camera_callback
    if area > min_area and aspect_ratio < 1: # Marker buoy has lower aspect ratio
UnboundLocalError: local variable 'min_area' referenced before assignment

[ERROR] [1649871760.878827, 10.620000]: bad callback: <bound method BuoyDetector.camera_callback of <singaboat_vrx.perception_module.BuoyDetector object at 0x7f3f8d260c70>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/VRX_Workspace/src/SINGABOAT-VRX/singaboat_vrx/src/singaboat_vrx/perception_module.py", line 266, in camera_callback
    if area > min_area and aspect_ratio < 1: # Marker buoy has lower aspect ratio
UnboundLocalError: local variable 'min_area' referenced before assignment

[ERROR] [1649871760.913470, 10.655000]: bad callback: <bound method BuoyDetector.camera_callback of <singaboat_vrx.perception_module.BuoyDetector object at 0x7f3f8d260c70>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/VRX_Workspace/src/SINGABOAT-VRX/singaboat_vrx/src/singaboat_vrx/perception_module.py", line 266, in camera_callback
    if area > min_area and aspect_ratio < 1: # Marker buoy has lower aspect ratio
UnboundLocalError: local variable 'min_area' referenced before assignment

[ERROR] [1649871760.952224, 10.687000]: bad callback: <bound method BuoyDetector.lidar_callback of <singaboat_vrx.perception_module.BuoyDetector object at 0x7f3f8d260c70>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/VRX_Workspace/src/SINGABOAT-VRX/singaboat_vrx/src/singaboat_vrx/perception_module.py", line 435, in lidar_callback
    pc_clusters = numpy.array(open3d_point_cloud.cluster_dbscan(eps=0.3, min_points=dbscan_min_points, print_progress=False))
UnboundLocalError: local variable 'dbscan_min_points' referenced before assignment

[ERROR] [1649871760.954212, 10.696000]: bad callback: <bound method BuoyDetector.camera_callback of <singaboat_vrx.perception_module.BuoyDetector object at 0x7f3f8d260c70>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/VRX_Workspace/src/SINGABOAT-VRX/singaboat_vrx/src/singaboat_vrx/perception_module.py", line 266, in camera_callback
    if area > min_area and aspect_ratio < 1: # Marker buoy has lower aspect ratio
UnboundLocalError: local variable 'min_area' referenced before assignment

[ERROR] [1649871760.976720, 10.718000]: bad callback: <bound method BuoyDetector.camera_callback of <singaboat_vrx.perception_module.BuoyDetector object at 0x7f3f8d260c70>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/VRX_Workspace/src/SINGABOAT-VRX/singaboat_vrx/src/singaboat_vrx/perception_module.py", line 266, in camera_callback
    if area > min_area and aspect_ratio < 1: # Marker buoy has lower aspect ratio
UnboundLocalError: local variable 'min_area' referenced before assignment

[ERROR] [1649871761.011494, 10.753000]: bad callback: <bound method BuoyDetector.camera_callback of <singaboat_vrx.perception_module.BuoyDetector object at 0x7f3f8d260c70>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/VRX_Workspace/src/SINGABOAT-VRX/singaboat_vrx/src/singaboat_vrx/perception_module.py", line 266, in camera_callback
    if area > min_area and aspect_ratio < 1: # Marker buoy has lower aspect ratio
UnboundLocalError: local variable 'min_area' referenced before assignment

[ERROR] [1649871761.053530, 10.788000]: bad callback: <bound method BuoyDetector.lidar_callback of <singaboat_vrx.perception_module.BuoyDetector object at 0x7f3f8d260c70>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/VRX_Workspace/src/SINGABOAT-VRX/singaboat_vrx/src/singaboat_vrx/perception_module.py", line 435, in lidar_callback
    pc_clusters = numpy.array(open3d_point_cloud.cluster_dbscan(eps=0.3, min_points=dbscan_min_points, print_progress=False))
UnboundLocalError: local variable 'dbscan_min_points' referenced before assignment

[ERROR] [1649871761.054096, 10.796000]: bad callback: <bound method BuoyDetector.camera_callback of <singaboat_vrx.perception_module.BuoyDetector object at 0x7f3f8d260c70>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/VRX_Workspace/src/SINGABOAT-VRX/singaboat_vrx/src/singaboat_vrx/perception_module.py", line 266, in camera_callback
    if area > min_area and aspect_ratio < 1: # Marker buoy has lower aspect ratio
UnboundLocalError: local variable 'min_area' referenced before assignment

[ERROR] [1649871761.076586, 10.818000]: bad callback: <bound method BuoyDetector.camera_callback of <singaboat_vrx.perception_module.BuoyDetector object at 0x7f3f8d260c70>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/VRX_Workspace/src/SINGABOAT-VRX/singaboat_vrx/src/singaboat_vrx/perception_module.py", line 266, in camera_callback
    if area > min_area and aspect_ratio < 1: # Marker buoy has lower aspect ratio
UnboundLocalError: local variable 'min_area' referenced before assignment

[ERROR] [1649871761.110365, 10.852000]: bad callback: <bound method BuoyDetector.camera_callback of <singaboat_vrx.perception_module.BuoyDetector object at 0x7f3f8d260c70>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/VRX_Workspace/src/SINGABOAT-VRX/singaboat_vrx/src/singaboat_vrx/perception_module.py", line 266, in camera_callback
    if area > min_area and aspect_ratio < 1: # Marker buoy has lower aspect ratio
UnboundLocalError: local variable 'min_area' referenced before assignment

[ERROR] [1649871761.144125, 10.886000]: bad callback: <bound method BuoyDetector.camera_callback of <singaboat_vrx.perception_module.BuoyDetector object at 0x7f3f8d260c70>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/VRX_Workspace/src/SINGABOAT-VRX/singaboat_vrx/src/singaboat_vrx/perception_module.py", line 266, in camera_callback
    if area > min_area and aspect_ratio < 1: # Marker buoy has lower aspect ratio
UnboundLocalError: local variable 'min_area' referenced before assignment

[ERROR] [1649871761.155389, 10.895000]: bad callback: <bound method BuoyDetector.lidar_callback of <singaboat_vrx.perception_module.BuoyDetector object at 0x7f3f8d260c70>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/VRX_Workspace/src/SINGABOAT-VRX/singaboat_vrx/src/singaboat_vrx/perception_module.py", line 435, in lidar_callback
    pc_clusters = numpy.array(open3d_point_cloud.cluster_dbscan(eps=0.3, min_points=dbscan_min_points, print_progress=False))
UnboundLocalError: local variable 'dbscan_min_points' referenced before assignment
```

**Comment by Tinker-Twins** [comment]
@caguero, we have updated the docker container image to resolve the issue. Kindly pull it again (extremely sorry for the repeated trouble caused) and confirm WAM-V activity after about 30 seconds (simulation time) have elapsed.

Once again, a review of all 6 tasks with those nice check-boxes as in https://github.com/osrf/vrx-events/pull/90#issuecomment-1098230486 will make our day! 😉

**Comment by M1chaelM** [comment]
Since it's very late in Spain I can take a look at this.

**Comment by M1chaelM** [comment]
Yes, I see the WAMV scanning back and forth for a bit and then it starts to go after about 40 seconds, so I will check the box on this.

**Comment by Tinker-Twins** [comment]
@M1chaelM or @caguero, could you please add those nice check-boxes as a final comment to this PR? It will make our day! 😉 Sorry for the trouble and thanks in advance! 😇

**Comment by M1chaelM** [comment]
Sorry I didn't see your request after we merged you. Here you go:

Verified that the WAMV is active in the following tasks:
* [x] Stationkeeping
* [x] Wayfinding
* [x] Perception 
* [x] Wildlife
* [x] Gymkhana
* [x] Scan, Dock, Deliver

**Comment by Tinker-Twins** [comment]
Absolutely no problem @M1chaelM. Thanks a lot! You did make our day! 😇

**Pull request merged**
