### PR TITLE
Team BYUVRX submission for 2022/phase3

### PR DESCRIPTION
**Pull request by Caden-Ellis77**
We expect competitive activity in tasks 1-4, and some activity in tasks 5 and 6.

### CODE REVIEW

**Comment by j-herman** [comment]
* [x] Compliance tests for component and propulsion configurations passed.
* [x] Successfully able to access Docker image.

Verified that the WAMV is active in the following tasks:
* [x] Stationkeeping
* [x] Wayfinding
* [x] Perception 
* [x] Wildlife
* [ ] Gymkhana
* [ ] Scan, Dock, Deliver 

I don't see the WAMV moving in the final two tasks - not sure if that is expected.

**Comment by j-herman** [comment]
@Caden-Ellis77 I'm going to merge this PR - it looks like everything is working correctly in the first four tasks.  If the behavior in tasks 5 and 6 is not what you were expecting and you want to make any changes, you are still welcome to submit a new PR up until the deadline.
Thanks for the submission!

**Comment by Caden-Ellis77** [comment]
What exactly was the behavior on 5 and 6? we are expecting it to just publish in 6 (not move), and we didn't expect a great score on 5 but we did expect movement.

**Comment by j-herman** [comment]
This was just a quick check to make sure all the pieces are communicating, so I just checked one run with a replay to see if the WAMV moved.  If you weren't expecting that in task 6, it's probably still working since tasks 1-4 looked good.  In task 5, I didn't see movement.  There weren't any unexpected errors in the run.

**Comment by Caden-Ellis77** [comment]
We resubmitted, we were missing a pinger for task 5.

**Pull request merged**
