### PR TITLE
Team Illusion VRX 2023 Hello World

### PR DESCRIPTION
**Pull request by thrzl**

### CODE REVIEW

**Review by caguero — CHANGES_REQUESTED** [review]
Thanks for your VRX submission!

* [ ] Compliance tests for component and propulsion configurations passed.
* [x] Successfully able to access Docker image.
* [x] Your video is reachable.
* [ ] Verified that the WAMV is active in the stationkeeping task.

There's a problem in the generation of your WAM-V. The `wamv_pinger` section should have a `sensor_name` field instead of `name`. 

We don't see activity in your WAM-V. Additionally, the following error has been found when running your submission:

```
tarting competitor container
---------------------------------
Creating container for teamillusion/vrx-competitor-example:2023.v1

docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/ros_entrypoint.sh": permission denied: unknown.
ERRO[0000] error waiting for container: context canceled
```

Please, update and retest your submission following the [instructions from the phase 1 tutorial](https://github.com/osrf/vrx/wiki/vrx_2023-phase1_hello_world#submission-testing).

**Comment by thrzl** [comment]
This fixes the WAM-V configuration issue, but I'm not sure about the Docker one; I can't reproduce it.

**Comment by ChaudiereNoire** [comment]
The problem with the image was permissions on the script file that had permission failures. We had to rebuild the docker image to fix that problem.

**Comment by ChaudiereNoire** [comment]
Is there some other action we have to take to get the changes we submitted reviewed? Our lead programmer fixed up the config file and we regenerated the Docker image to fix up the permissions.

**Review by caguero — APPROVED** [review]
Your WAM-V generates successfully now and I can see some WAM-V activity during `stationkeeping`. Approving!

**Comment by ChaudiereNoire** [comment]
Thank you. I should leave the image to the students. It was a demo I was doing that toasted the trial image. It gave me a teaching moment.

**Pull request merged**
