### PR TITLE
Team Robotics and Circuits submission for 2022/troubleshooting.

### PR DESCRIPTION
**Pull request by RishabhRishiRishu**
We have prepared the docker image as per the latest instructions given but the wam-v still remains in the same position. Meanwhile, we are also trying to sort this issue out from our side.

### CODE REVIEW

**Comment by M1chaelM** [comment]
I'm also seeing a motionless WAMV. However, I can confirm that your image is running during the trial and when I log into it I'm able to manually list topics and echo the `/vrx/task/info`. If you are stuck, it may be helpful to try to run a trial manually if you haven't done this already. It takes a little work but I've written up a tutorial about it here: https://github.com/osrf/vrx/wiki/tutorials-vrx_docker_manual_trial

**Comment by M1chaelM** [comment]
I looked into this a little further. When I run your Python scripts manually in the trial they work fine. I think the issue is just that your `run_my_system.bash` script is using a variable called `TASK` but you never set that variable, so the call to `python3 $TASK*.py` fails. In other words, `TASK` is not part of the default environment. Your system is expected to determine which task is running and then execute the code for that task.

The good news is that there is an example of how to do this. Take a look at the `run_my_system.bash` and `basic_node.py` that are included in the `vrx_2022_starter` example, here: https://github.com/osrf/vrx-docker/tree/master/mwes/2022/vrx_2022_starter

**Comment by RishabhRishiRishu** [comment]
We've updated the image according to the above instructions, can you let us know if it's working properly.

**Comment by M1chaelM** [comment]
* [x] Compliance tests for component and propulsion configurations passed.
* [x] Successfully able to access Docker image.

Verified that the WAMV is active in the following tasks:
* [x] Stationkeeping
* [x] Wayfinding
* [ ] Perception 
* [x] Wildlife
* [ ] Gymkhana
* [ ] Scan, Dock, Deliver

**Comment by M1chaelM** [comment]
I checked on all 6 tasks and I can see activity on the 3 marked above. If this expected I think your infrastructure is working and we can probably merge this. But, if there's anything else you want me to test first let me know.

**Pull request merged**
