### PR TITLE
Team FRL submission for 2023/phase2

### PR DESCRIPTION
**Pull request by YvonneoO**
The submission tackles task#1 station keeping, it won't work for all other tasks.

### CODE REVIEW

**Review by caguero — APPROVED** [review]
Thanks for your VRX submission!

* [x] Compliance tests for component and propulsion configurations passed.
* [x] Successfully able to access Docker image.
* [x] Verified that the WAMV is active in the stationkeeping task.

All looking good!

**Review by caguero — CHANGES_REQUESTED** [review]
Minor request:

Could you leave your phase1 files untouched? This pull request should only contribute to phase2 in your case.

**Comment by YvonneoO** [comment]
Hi, files for phase 1 have been removed for this pull request. 

One more thing, we are facing issues when testing our solution following this tutorial https://github.com/osrf/vrx/wiki/vrx_2023-testing. /vrx/task/info topic works fine, but all sensor topics from the vrx-server container are not available. 

However, it seems the testing and evaluation were successful on your side. I saw a discussion about this in Discord as well. Is there any update about this issue for now?

**Review by caguero — APPROVED** [review]

**Comment by caguero** [comment]
> One more thing, we are facing issues when testing our solution following this tutorial https://github.com/osrf/vrx/wiki/vrx_2023-testing. /vrx/task/info topic works fine, but all sensor topics from the vrx-server container are not available.
> 
> However, it seems the testing and evaluation were successful on your side. I saw a discussion about this in Discord as well. Is there any update about this issue for now?

I can't reproduce this issue but we have other members of the technical team trying it out as well. We'll report on Discord after their findings.

**Comment by YvonneoO** [comment]
> > One more thing, we are facing issues when testing our solution following this tutorial https://github.com/osrf/vrx/wiki/vrx_2023-testing. /vrx/task/info topic works fine, but all sensor topics from the vrx-server container are not available.
> > However, it seems the testing and evaluation were successful on your side. I saw a discussion about this in Discord as well. Is there any update about this issue for now?
> 
> I can't reproduce this issue but we have other members of the technical team trying it out as well. We'll report on Discord after their findings.

alright, thanks!

**Pull request merged**
