### PR TITLE
Team Robotics and Circuits submission for 2022/dress_rehearsal event.

### PR DESCRIPTION
**Pull request by RishabhRishiRishu**
This submission attempts tasks #1, #2, #3, #4, which work as intended on local setup, but has some issues with the docker. This issue may result from being unable to subscribe to a few topics related to goal-pose in docker.
(Goal pose is not visible during test runs) . We'll try to debug it in the next round.

### CODE REVIEW

**Comment by M1chaelM** [comment]
* [x] Compliance tests for component and propulsion configurations passed.
* [x] Successfully able to access Docker image.

Verified that the WAMV is active in the following tasks:
* [ ] Stationkeeping
* [ ] Wayfinding
* [ ] Perception 
* [ ] Wildlife
* [ ] Gymkhana
* [ ] Scan, Dock, Deliver

**Comment by M1chaelM** [comment]
In initial tests, I am seeing the WAMV move forward in a straight line in the stationkeeping task. I can check other tasks, but it appears that you are using the example image produced by the tutorial. If you made further changes, is it possible you may not have committed them before pushing your image to the repository?

**Comment by RishabhRishiRishu** [comment]
We are looking into the issue. It's our first time using docker. The system was working as intended in the local setup but we are facing issues in setting up the docker file. We will try to resolve the issue as soon as possible.

**Comment by M1chaelM** [comment]
Please let me know if I can help troubleshoot!

**Comment by RishabhRishiRishu** [comment]
We followed option 1 of the docker tutorial. Seems like we are unable to put the source files into docker image. It will be great if you can help us troubleshoot.

**Comment by M1chaelM** [comment]
OK, sure. If you are using option 1, the most basic approach is paste code directly into the editor running in the terminal, and save it. If that is unwieldy and you already have the files on your host system you could also use the `docker cp` command to get them into the container:

https://docs.docker.com/engine/reference/commandline/cp/

For example:
```
docker cp script.py container_name:/where/you/want/it/
```
Once you make a change to the running container, you will still need to use the docker commit command (as described in the tutorial) to make the change persistent. Once the code is in the container, you will initiate it from the ros_entrypoint.sh file so it starts when the container is run. If your code relies on your own ros workspace you'll need to source the `setup.bash` file for that workspace.

**Comment by RishabhRishiRishu** [comment]
I was trying option 2 also, where it seemed like the files were copied to the image.

On trying option 2 I got stuck at the following:

The specified source space "/src" does not exist
Base path: /
/run_my_system.sh: line 54: /vrx_ws/src/vrx/vrx_gazebo/launch/station_keeping.launch: Permission denied
Traceback (most recent call last):
  File "/vrx_ws/src/vrx/vrx_gazebo/scripts/stationkeeping.py", line 6, in <module>
    from geographic_msgs.msg import GeoPoseStamped
ModuleNotFoundError: No module named 'geographic_msgs'

**Comment by M1chaelM** [comment]
If you are using option 2 may I see your Dockerfile? You could post here or email it to me, or if it's in a repository just send me a link.

**Comment by RishabhRishiRishu** [comment]
I have sent you a link to all the files by mail. Please let me know if there is any issue in accessing it.

**Comment by M1chaelM** [comment]
> I have sent you a link to all the files by mail. Please let me know if there is any issue in accessing it.

I have responded with some troubleshooting suggestions. Let me know if you would like me to test again. Otherwise I will merge this PR.

**Comment by RishabhRishiRishu** [comment]
We have tried making the docker file and have changed the tag. But on testing it (which took about an hour) we weren't able to pull a container which was required. We request you to merge this PR.
Our team is immensely thankful for your help. We'll try our best to resolve all the issues and get it working.

**Comment by M1chaelM** [comment]
OK, I will test once more and then merge. I can't quite tell from your description, but you should not be required to pull any containers for testing except your own, so I wonder if the white space in your team name might be causing you some trouble. In any case, we will also work on this aspect of the competition between now and the finals.

**Review by M1chaelM — APPROVED** [review]
I'm still not seeing WAMV movement, but I am going to approve this for merging as requested. We will be in touch about additional docker support before the final phase of the competition.

**Pull request merged**
