### PR TITLE
Phase 2 Submission PENShip

### PR DESCRIPTION
**Pull request by rlggyp**

### CODE REVIEW

**Review by caguero — COMMENTED** [review]
Thanks for your VRX submission!

* [x] Your video is reachable.
* [x] Compliance tests for component and propulsion configurations passed.
* [x] Successfully able to access Docker image.
* [ ] Verified that the WAMV is active in the stationkeeping task.

I don't see activity in your WAM-V during stationkeeping as the propellers don't move at all.

If this isn't expected behavior, please update and retest your submission following the [instructions from the phase 2 tutorial](https://github.com/osrf/vrx/wiki/vrx_2023-phase2_dress_rehearsal#submission-testing).

**Comment by rlggyp** [comment]
Thank you for reviewing,

Here is a [video](https://youtu.be/aLOAFiXiCZ8) of me performing a stationkeeping task, and the propellers are working fine.

**Comment by rlggyp** [comment]
May i ask, did you already run my custom launch file?
```bash
ros2 launch launcher station_keeping.launch.xml
```

**Comment by caguero** [comment]
> May i ask, did you already run my custom launch file?
> 
> ```shell
> ros2 launch launcher station_keeping.launch.xml
> ```

No, we're not supposed to launch any custom files. You should follow the conventions described in https://github.com/osrf/vrx/wiki/vrx_2023-phase2_dress_rehearsal#submission-process . That way, your solution will be executed automatically. Please, make sure you understand this process for phase 3.

Approving, as your submission is functional, although not controlling the WAM-V.

**Review by caguero — APPROVED** [review]

**Pull request merged**
