### PR TITLE
2023 Phase3 Team FRL submission

### PR DESCRIPTION
**Pull request by YvonneoO**
Our team attempted tasks 1, 2, 3, 4, 5, and 7. We have some issues when testing our solutions with vrx-docker. Could you verify if the wamv moves reasonably on your side?

### CODE REVIEW

**Review by caguero — CHANGES_REQUESTED** [review]
Thanks for your submission!

* [ ] Compliance tests for component and propulsion configurations passed.
* [x] Successfully able to access Docker image.
* [ ] Verified that the WAMV is active in the stationkeeping task

Your submission is not committing the `thruster_config.yaml` file under the `phase3_vrx_challenge/<YOUR_TEAM_NAME>` directory. Please, commit it within the next 24 hours inside your team directory within the other two files. 

https://github.com/osrf/vrx/wiki/vrx_2023-phase3_challenge#submission-format

I manually placed `thruster_config.yaml` in the right directory and ran your WAMV-generation but it's not generating the WAM-V correctly. Verify this section from the instructions

https://github.com/osrf/vrx/wiki/vrx_2023-phase3_challenge#submission-process

You're configuring your WAM-V with two ball launchers and four cameras. Only one ball launcher and three cameras are allowed. You might have other issues.

**Comment by YvonneoO** [comment]
hi, sorry for the formatting issues. I've put them all under the folder. And for the component config, our WAM-V is using the default configuration, I uploaded the wrong file. I've gone through the testing tutorials, I think it should work for now.

**Comment by caguero** [comment]
> hi, sorry for the formatting issues. I've put them all under the folder. And for the component config, our WAM-V is using the default configuration, I uploaded the wrong file. I've gone through the testing tutorials, I think it should work for now.

It looks like your thruster configuration is invalid:

```
[generate_wamv.py-1] [INFO] [1699034914.322821677] [configure_wamv]: 
[generate_wamv.py-1] Using /home/caguero/vrx2023_ws/src/vrx-docker/team_config/FRL/thruster_config.yaml as the thruster configuration yaml file
[generate_wamv.py-1] 
[generate_wamv.py-1] [INFO] [1699034914.323125692] [configure_wamv]: 
[generate_wamv.py-1] Trying to open /home/caguero/vrx2023_ws/src/vrx-docker/team_config/FRL/thruster_config.xacro 
[generate_wamv.py-1] 
[generate_wamv.py-1] [ERROR] [1699034914.327333181] [compliance]: engine left_f is out of bounds
[generate_wamv.py-1] [ERROR] [1699034914.327607715] [compliance]: engine left_f is at xyz=(2.373776, 1.027135, 0.318237), it must fit in at least one of the following boxes with remaining space:
[generate_wamv.py-1] [ERROR] [1699034914.327881019] [compliance]:   <Box name:thruster_compliance_port_aft x:[-1.75, -2.75] y:[1.5,0.5] z:[0.6,-0.6]                remaining_space:0>
[generate_wamv.py-1] [ERROR] [1699034914.328143333] [compliance]:   <Box name:thruster_compliance_star_aft x:[-1.75, -2.75] y:[-0.5,-1.5] z:[0.6,-0.6]                remaining_space:0>
[generate_wamv.py-1] [ERROR] [1699034914.328405297] [compliance]:   <Box name:thruster_compliance_port_for x:[1.75, 0.75] y:[1.5,0.5] z:[0.6,-0.6]                remaining_space:1>
[generate_wamv.py-1] [ERROR] [1699034914.328681560] [compliance]:   <Box name:thruster_compliance_star_for x:[1.75, 0.75] y:[-0.5,-1.5] z:[0.6,-0.6]                remaining_space:1>
[generate_wamv.py-1] [ERROR] [1699034914.328945554] [compliance]:   <Box name:thruster_compliance_middle x:[1.5, -1.0] y:[0.5,-0.5] z:[0.6,-0.6]                remaining_space:1>
[generate_wamv.py-1] [ERROR] [1699034914.329225838] [compliance]: engine right_f is out of bounds
[generate_wamv.py-1] [ERROR] [1699034914.329486132] [compliance]: engine right_f is at xyz=(2.373776, -1.027135, 0.318237), it must fit in at least one of the following boxes with remaining space:
[generate_wamv.py-1] [ERROR] [1699034914.329749996] [compliance]:   <Box name:thruster_compliance_port_aft x:[-1.75, -2.75] y:[1.5,0.5] z:[0.6,-0.6]                remaining_space:0>
[generate_wamv.py-1] [ERROR] [1699034914.330012590] [compliance]:   <Box name:thruster_compliance_star_aft x:[-1.75, -2.75] y:[-0.5,-1.5] z:[0.6,-0.6]                remaining_space:0>
[generate_wamv.py-1] [ERROR] [1699034914.330274913] [compliance]:   <Box name:thruster_compliance_port_for x:[1.75, 0.75] y:[1.5,0.5] z:[0.6,-0.6]                remaining_space:1>
[generate_wamv.py-1] [ERROR] [1699034914.330535917] [compliance]:   <Box name:thruster_compliance_star_for x:[1.75, 0.75] y:[-0.5,-1.5] z:[0.6,-0.6]                remaining_space:1>
[generate_wamv.py-1] [ERROR] [1699034914.330798001] [compliance]:   <Box name:thruster_compliance_middle x:[1.5, -1.0] y:[0.5,-0.5] z:[0.6,-0.6]                remaining_space:1>
[generate_wamv.py-1] [INFO] [1699034914.332133880] [configure_wamv]: 
[generate_wamv.py-1] Using /home/caguero/vrx2023_ws/src/vrx-docker/team_config/FRL/component_config.yaml as the component configuration yaml file
[generate_wamv.py-1] 
[generate_wamv.py-1] [ERROR] [1699034914.539689417] [configure_wamv]: 
[generate_wamv.py-1] This component/thruster configuration is NOT compliant with the (current) VRX constraints. A urdf file will be created, but please note that the above errors must be fixed for this to be a valid configuration for the VRX competition.
[generate_wamv.py-1]
```

**Comment by YvonneoO** [comment]
> > hi, sorry for the formatting issues. I've put them all under the folder. And for the component config, our WAM-V is using the default configuration, I uploaded the wrong file. I've gone through the testing tutorials, I think it should work for now.
> 
> It looks like your thruster configuration is invalid:
> 
> ```
> [generate_wamv.py-1] [INFO] [1699034914.322821677] [configure_wamv]: 
> [generate_wamv.py-1] Using /home/caguero/vrx2023_ws/src/vrx-docker/team_config/FRL/thruster_config.yaml as the thruster configuration yaml file
> [generate_wamv.py-1] 
> [generate_wamv.py-1] [INFO] [1699034914.323125692] [configure_wamv]: 
> [generate_wamv.py-1] Trying to open /home/caguero/vrx2023_ws/src/vrx-docker/team_config/FRL/thruster_config.xacro 
> [generate_wamv.py-1] 
> [generate_wamv.py-1] [ERROR] [1699034914.327333181] [compliance]: engine left_f is out of bounds
> [generate_wamv.py-1] [ERROR] [1699034914.327607715] [compliance]: engine left_f is at xyz=(2.373776, 1.027135, 0.318237), it must fit in at least one of the following boxes with remaining space:
> [generate_wamv.py-1] [ERROR] [1699034914.327881019] [compliance]:   <Box name:thruster_compliance_port_aft x:[-1.75, -2.75] y:[1.5,0.5] z:[0.6,-0.6]                remaining_space:0>
> [generate_wamv.py-1] [ERROR] [1699034914.328143333] [compliance]:   <Box name:thruster_compliance_star_aft x:[-1.75, -2.75] y:[-0.5,-1.5] z:[0.6,-0.6]                remaining_space:0>
> [generate_wamv.py-1] [ERROR] [1699034914.328405297] [compliance]:   <Box name:thruster_compliance_port_for x:[1.75, 0.75] y:[1.5,0.5] z:[0.6,-0.6]                remaining_space:1>
> [generate_wamv.py-1] [ERROR] [1699034914.328681560] [compliance]:   <Box name:thruster_compliance_star_for x:[1.75, 0.75] y:[-0.5,-1.5] z:[0.6,-0.6]                remaining_space:1>
> [generate_wamv.py-1] [ERROR] [1699034914.328945554] [compliance]:   <Box name:thruster_compliance_middle x:[1.5, -1.0] y:[0.5,-0.5] z:[0.6,-0.6]                remaining_space:1>
> [generate_wamv.py-1] [ERROR] [1699034914.329225838] [compliance]: engine right_f is out of bounds
> [generate_wamv.py-1] [ERROR] [1699034914.329486132] [compliance]: engine right_f is at xyz=(2.373776, -1.027135, 0.318237), it must fit in at least one of the following boxes with remaining space:
> [generate_wamv.py-1] [ERROR] [1699034914.329749996] [compliance]:   <Box name:thruster_compliance_port_aft x:[-1.75, -2.75] y:[1.5,0.5] z:[0.6,-0.6]                remaining_space:0>
> [generate_wamv.py-1] [ERROR] [1699034914.330012590] [compliance]:   <Box name:thruster_compliance_star_aft x:[-1.75, -2.75] y:[-0.5,-1.5] z:[0.6,-0.6]                remaining_space:0>
> [generate_wamv.py-1] [ERROR] [1699034914.330274913] [compliance]:   <Box name:thruster_compliance_port_for x:[1.75, 0.75] y:[1.5,0.5] z:[0.6,-0.6]                remaining_space:1>
> [generate_wamv.py-1] [ERROR] [1699034914.330535917] [compliance]:   <Box name:thruster_compliance_star_for x:[1.75, 0.75] y:[-0.5,-1.5] z:[0.6,-0.6]                remaining_space:1>
> [generate_wamv.py-1] [ERROR] [1699034914.330798001] [compliance]:   <Box name:thruster_compliance_middle x:[1.5, -1.0] y:[0.5,-0.5] z:[0.6,-0.6]                remaining_space:1>
> [generate_wamv.py-1] [INFO] [1699034914.332133880] [configure_wamv]: 
> [generate_wamv.py-1] Using /home/caguero/vrx2023_ws/src/vrx-docker/team_config/FRL/component_config.yaml as the component configuration yaml file
> [generate_wamv.py-1] 
> [generate_wamv.py-1] [ERROR] [1699034914.539689417] [configure_wamv]: 
> [generate_wamv.py-1] This component/thruster configuration is NOT compliant with the (current) VRX constraints. A urdf file will be created, but please note that the above errors must be fixed for this to be a valid configuration for the VRX competition.
> [generate_wamv.py-1]
> ```

will have a look into it. just to confirm, we are able to resubmit until 24hrs from your 1st review right?

**Comment by caguero** [comment]
> will have a look into it. just to confirm, we are able to resubmit until 24hrs from your 1st review right?

That's correct!

**Comment by YvonneoO** [comment]
> > will have a look into it. just to confirm, we are able to resubmit until 24hrs from your 1st review right?
> 
> That's correct!

We've submitted the modified version. Thanks for the instructions!

**Comment by caguero** [comment]
> > > will have a look into it. just to confirm, we are able to resubmit until 24hrs from your 1st review right?
> > 
> > 
> > That's correct!
> 
> We've submitted the modified version. Thanks for the instructions!

And it's working now, good job!

The next step is to evaluate the docker image in the VRX simulation with the tasks/trials over the next few days.

Good luck!

**Review by caguero — APPROVED** [review]

**Pull request merged**
