### PR TITLE
Team ITUASTEAM submission for 2022/rehearsal event.

### PR DESCRIPTION
**Pull request by otonomteknetakimi**
ITUASTEAM

### CODE REVIEW

**Comment by M1chaelM** [comment]
* [x] Compliance tests for component and propulsion configurations passed.
* [x] Successfully able to access Docker image.

Verified that the WAMV is active in the following tasks:
* [ ] Stationkeeping
* [ ] Wayfinding
* [ ] Perception 
* [ ] Wildlife
* [ ] Gymkhana
* [ ] Scan, Dock, Deliver

**Comment by otonomteknetakimi** [comment]
We updated the docker and try to test now

**Review by caguero — COMMENTED** [review]
I tested your submission with the stationkeeping task. Unfortunately I don't see any movement in your WAM-V.

**Review by caguero — APPROVED** [review]
I am going to approve your submission. We will be in touch about additional docker support before the final phase of the competition.

**Pull request merged**
