### PR TITLE
Team Wazzu Worms submission for 2022/troubleshooting event.

### PR DESCRIPTION
**Pull request by FrancisGoncalves**

### CODE REVIEW

**Comment by caguero** [comment]
Hi @FrancisGoncalves , considering that we're in the troubleshooting week, could you please describe the expectations of your submission (e.g. it should work for all tasks, it should only work for the station keeping task, ...), the last known issues and your last actions?

**Comment by FrancisGoncalves** [comment]
Hi,

It should work for tasks 1 and 2. The last known issue with the docker image was that our python scripts immediately stopped after being launched, and we could not figure out why.

Thank you,
Francisco



________________________________

**Comment by caguero** [comment]
I strongly suggest that you review the new set of tutorials described here:

https://github.com/osrf/vrx/wiki/tutorials-vrx_competitor_image

Let us know what isn't clear and we'll help.

**Comment by FrancisGoncalves** [comment]
Okay, we are doing that right now. I will let you know how it goes.

Thank you,
Francisco
________________________________

**Comment by M1chaelM** [comment]
Closing this in favor of #70

**Pull request closed without merging**
