### PR TITLE
2022 Team Bumblebee submission

### PR DESCRIPTION
**Pull request by Amadeus-Winarto**
This submission attempts tasks 1, 2, 3, 4, 5 and 6

### CODE REVIEW

**Review by caguero — CHANGES_REQUESTED** [review]
Thanks for the submission! 

I don't have permissions to access your Docker image. If this is private, could you grant access to the `virtualrobotx` user?

**Comment by gok99** [comment]
Oops apologies @caguero, it should be accessible now!

**Comment by j-herman** [comment]
* [x] Compliance tests for component and propulsion configurations passed.
* [x] Successfully able to access Docker image.

Verified that the WAMV is active in the following tasks:
* [x] Stationkeeping
* [x] Wayfinding
* [x] Perception 
* [x] Wildlife
* [x] Gymkhana
* [x] Scan, Dock, Deliver

**Comment by j-herman** [comment]
All seems to be communicating correctly and we can access the image.  Thanks for the submission!

**Pull request merged**
