### PR TITLE
2022 rehearsal USYD RobotX

### PR DESCRIPTION
**Pull request by JohnSumskas**
Usyd RobotX Submission to Phase 2

### CODE REVIEW

**Comment by M1chaelM** [comment]
* [x] Compliance tests for component and propulsion configurations passed.
* [x] Successfully able to access Docker image.

Verified that the WAMV is active in the following tasks:
* [x] Stationkeeping
* [x] Wayfinding
* [ ] Perception 
* [ ] Wildlife
* [ ] Gymkhana
* [ ] Scan, Dock, Deliver

**Comment by M1chaelM** [comment]
Thanks for your submission. Could you say which tasks you've attempted?

**Comment by M1chaelM** [comment]
I am seeing activity on tasks 1 and 2, but not 3, 4, 5 or 6. Could you confirm that is what you expect? If so, we are ready to accept.

**Comment by JohnSumskas** [comment]
Yes that is expected

**Review by M1chaelM — APPROVED** [review]
Great, thanks! Also thank you for the submission! The next step is to evaluate run the docker image in the VRX simulation with the tasks/trials over the next few days.

**Pull request merged**
