### PR TITLE
Team Aritra submission for 2023/phase1 event.

### PR DESCRIPTION
**Pull request by AritraOceana**
The submitted image doesn't have solutions of any of the tasks currently.

### CODE REVIEW

**Review by caguero — COMMENTED** [review]
Thanks for your VRX submission!

* [x] Compliance tests for component and propulsion configurations passed.
* [x] Successfully able to access Docker image.
* [x] Your video is reachable.
* [ ] Verified that the WAMV is active in the stationkeeping task.

We don't see activity in your WAM-V in the `stationkeeping` task. Is this expected?

**Comment by AritraOceana** [comment]
Yes. Currently we haven't included the solution of any of the tasks in the docker image so no activity is expected.

**Comment by AritraOceana** [comment]
Do let us know if it required to attempt the station keeping task in the docker image for qualification in this round.

**Review by caguero — APPROVED** [review]
Your're good then! Approving.

I recommend you to go through the submission [instructions from the phase 1 tutorial](https://github.com/osrf/vrx/wiki/vrx_2023-phase1_hello_world#submission-testing) to test your solution (when ready) before phase 2. You can do that by yourself to make sure things are working before you make the next submission.

**Pull request merged**
