### PR TITLE
Team IMU-VRX submission for 2022/vrx challenge event.

### PR DESCRIPTION
**Pull request by MustafaBayrak1**
"This submission tackles tasks #1, #2, #3, #5 and #6 but it won't work for task #4. 

Team IMU-VRX VRX2022 Final event submission.

### CODE REVIEW

**Comment by M1chaelM** [comment]
* [x] Compliance tests for component and propulsion configurations passed.
* [x] Successfully able to access Docker image.

Verified that the WAMV is active in the following tasks:
* [x] Stationkeeping
* [x] Wayfinding
* [x] Perception 
* [ ] Wildlife
* [ ] Gymkhana
* [x] Scan, Dock, Deliver

**Comment by M1chaelM** [comment]
I'm not seeing any obvious WAMV activity in task 3, 5 or 6. For task 5 I don't see any output, but in tasks 3 and 6, I see output that looks like this:
```
Sending forward command
qt.qpa.xcb: could not connect to display 
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, xcb.

/run_my_system.bash: line 18:    63 Aborted                 (core dumped) python3 mission_executer.py
```

**Comment by MustafaBayrak1** [comment]
I am sorry for inconvenience. I fixed the issue and updated the docker image name on our submission file. For mission 3 and 6, it should work. For mission 5, I couldn't solve the issue, so we decided to abort it.

**Comment by M1chaelM** [comment]
OK, I'm now seeing some signs of activity in perception (task 3). The scan, dock and deliver task (6) still does not move. I get error output that looks like:

```
[ERROR] [1649821471.730550, 4.566000]: bad callback: <bound method Bot.getPointCloud of <dock_node.Bot object at 0x7f523f8d8970>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/dock_node.py", line 122, in getPointCloud
    target_coordinates, dock_left, dock_right = dock_processing.main(self.image, self.image_points, self.xyz_points)
  File "/dock_processing.py", line 251, in main
    blue = scan_light(img, lower_blue, upper_blue, "blue")
  File "/dock_processing.py", line 51, in scan_light
    hsv = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)
TypeError: Expected cv::UMat for argument 'src'

```

**Comment by MustafaBayrak1** [comment]
Thanks for the respond. I updated the dockerhub_image.txt. It shouldn't give error and successfully read the light buoy and publish to the service.

I am having storage issues on my computer so I can't test on docker but when i test the code on my host machine via example trials, it works. Thanks again for your support. We really appreciate it.

**Comment by j-herman** [comment]
I ran task 6 and confirmed that your image is now publishing to the service.  Glad you were able to find the issue!

**Comment by M1chaelM** [comment]
I think we are now seeing the expected activity on all tasks, so this is ready to merge. I did try a longer run of the gymkhana task and I noticed I get an error message for each second of the trial time that looks like this:
```
[ERROR] [1649878126.389127, 266.005000]: unsupported operand type(s) for /: 'str' and 'int'
```
I'll wait to hear from you (or until the deadline for corrections tonight at 11:59 PT) before merging in case you have anything else to add.

**Comment by MustafaBayrak1** [comment]
Yes, we are now seeing the expected activity on all tasks. It is ready to merge.

**Pull request merged**
